export interface ModuleLevel {
  id: string;
  number: number;
  tier: 0 | 1 | 2 | 3 | 4;
  title: string;
  notion: string;
  difficulty: 0 | 1 | 2 | 3 | 4;   // 0=QCM · 1=★ · 2=★★ · 3=★★★ · 4=◆
  timeMin: number;
  description: string;
  xpReward: number;
}

export interface PhysicsModule {
  id: string;
  subject: 'Physique' | 'Maths';
  level: string;            // e.g. "Terminale"
  title: string;
  subtitle: string;
  accentHsl: string;
  pdfCours: string | null;
  pdfFiche: string | null;
  pdfExercices: string | null;
  levels: ModuleLevel[];
}

// ─── Module 1 : Newton & champ uniforme ────────────────────────────────────
const NEWTON_LEVELS: ModuleLevel[] = [
  // ── TIER 0 — QCM ─────────────────────────────────────────────────────────
  {
    id: 'newton-qcm',
    number: 0,
    tier: 0,
    title: 'QCM Flash',
    notion: 'Tout le cours',
    difficulty: 0,
    timeMin: 15,
    description: '12 questions pour vérifier que le cours est en place avant de passer aux exercices.',
    xpReward: 30,
  },
  // ── TIER 1 — Automatismes ★ ───────────────────────────────────────────────
  {
    id: 'newton-1',
    number: 1,
    tier: 1,
    title: 'Dériver un vecteur position',
    notion: 'Cinématique',
    difficulty: 1,
    timeMin: 8,
    description: 'Calculer vitesse et accélération à partir de OM(t) = 2t·i + (3t²−t)·j.',
    xpReward: 40,
  },
  {
    id: 'newton-2',
    number: 2,
    tier: 1,
    title: 'Du vecteur vitesse à la position',
    notion: 'Intégration',
    difficulty: 1,
    timeMin: 8,
    description: 'Intégrer v(t) pour retrouver les équations horaires x(t) et y(t).',
    xpReward: 40,
  },
  {
    id: 'newton-3',
    number: 3,
    tier: 1,
    title: 'Faire le bilan des forces',
    notion: 'Forces',
    difficulty: 1,
    timeMin: 7,
    description: 'Inventaire et schéma des forces sur un solide posé sur un plan incliné sans frottement.',
    xpReward: 40,
  },
  {
    id: 'newton-4',
    number: 4,
    tier: 1,
    title: 'Écrire et projeter la 2e loi',
    notion: 'Méthode',
    difficulty: 1,
    timeMin: 9,
    description: "Bilan des forces sur une bille avec frottement, puis projection pour calculer l'accélération.",
    xpReward: 40,
  },
  {
    id: 'newton-5',
    number: 5,
    tier: 1,
    title: 'Intégrer pour obtenir les équations horaires',
    notion: 'Intégration',
    difficulty: 1,
    timeMin: 8,
    description: "À partir d'une accélération constante et des conditions initiales, remonter à v(t) puis OM(t).",
    xpReward: 40,
  },
  {
    id: 'newton-6',
    number: 6,
    tier: 1,
    title: "Le principe d'inertie",
    notion: '1re loi',
    difficulty: 1,
    timeMin: 6,
    description: 'Palet sur la glace et livre sur une table : énoncer et appliquer la 1re loi de Newton.',
    xpReward: 40,
  },
  {
    id: 'newton-7',
    number: 7,
    tier: 1,
    title: 'Action et réaction',
    notion: '3e loi',
    difficulty: 1,
    timeMin: 7,
    description: 'Identifier les paires action–réaction et distinguer forces sur le même corps / corps différents.',
    xpReward: 40,
  },
  {
    id: 'newton-8',
    number: 8,
    tier: 1,
    title: 'Champ, tension et force',
    notion: 'Champ E',
    difficulty: 1,
    timeMin: 6,
    description: 'Calculer E = U/d puis la force sur un électron dans un condensateur (d=2 cm, U=1 kV).',
    xpReward: 40,
  },
  {
    id: 'newton-9',
    number: 9,
    tier: 1,
    title: "Accélération d'une particule chargée",
    notion: 'Champ E',
    difficulty: 1,
    timeMin: 7,
    description: "Calculer l'accélération d'un électron dans un champ E = 1 000 V·m⁻¹ et déterminer son sens.",
    xpReward: 40,
  },
  // ── TIER 2 — Méthodes ★★ ─────────────────────────────────────────────────
  {
    id: 'newton-10',
    number: 10,
    tier: 2,
    title: 'Chute libre verticale',
    notion: 'Méthode',
    difficulty: 2,
    timeMin: 12,
    description: "Méthode 5 étapes sur une chute depuis h=20 m : durée, vitesse à l'impact.",
    xpReward: 70,
  },
  {
    id: 'newton-11',
    number: 11,
    tier: 2,
    title: 'Plan incliné sans frottement',
    notion: 'Méthode',
    difficulty: 2,
    timeMin: 14,
    description: 'Solide sur plan incliné (β=20°) : bilan des forces, projection, a = g sin β, équations horaires.',
    xpReward: 70,
  },
  {
    id: 'newton-12',
    number: 12,
    tier: 2,
    title: 'Le projectile complet',
    notion: 'Projectile',
    difficulty: 2,
    timeMin: 18,
    description: "Footballeur (v₀=15 m/s, α=40°) : équations horaires, trajectoire, flèche, portée, franchissement d'un mur.",
    xpReward: 70,
  },
  {
    id: 'newton-13',
    number: 13,
    tier: 2,
    title: 'Tir horizontal depuis une hauteur',
    notion: 'Projectile',
    difficulty: 2,
    timeMin: 14,
    description: "Balle lancée horizontalement (v₀=8 m/s) du haut d'une falaise (h=20 m) : durée, distance, vitesse à l'impact.",
    xpReward: 70,
  },
  {
    id: 'newton-14',
    number: 14,
    tier: 2,
    title: "Vitesse d'un électron dévié",
    notion: 'Champ E',
    difficulty: 2,
    timeMin: 16,
    description: 'Électron dans un condensateur (L=4 cm, E=10⁴ V/m) : accélération, composante vy et norme de v à la sortie.',
    xpReward: 70,
  },
  {
    id: 'newton-15',
    number: 15,
    tier: 2,
    title: 'Déflexion dans un condensateur',
    notion: 'Champ E',
    difficulty: 2,
    timeMin: 16,
    description: "Trajectoire d'un électron entre deux plaques (U=200 V, d=2 cm, L=5 cm) : déviation et vérification qu'il ne touche pas les plaques.",
    xpReward: 70,
  },
  // ── TIER 3 — Type Bac ★★★ ────────────────────────────────────────────────
  {
    id: 'newton-16',
    number: 16,
    tier: 3,
    title: 'Le lancer franc',
    notion: 'Type Bac',
    difficulty: 3,
    timeMin: 22,
    description: 'Lancer franc de basket (v₀=7,3 m/s, α=52°, D=4,20 m, h_panier=3,05 m) : trajectoire, hauteur au panier, sens du mouvement.',
    xpReward: 100,
  },
  {
    id: 'newton-17',
    number: 17,
    tier: 3,
    title: 'Le saut en longueur',
    notion: 'Type Bac',
    difficulty: 3,
    timeMin: 20,
    description: "Saut en longueur (v₀=9,5 m/s, α=22°) : flèche, portée, optimisation de l'angle pour 7 m.",
    xpReward: 100,
  },
  {
    id: 'newton-18',
    number: 18,
    tier: 3,
    title: "L'oscilloscope cathodique",
    notion: 'Type Bac',
    difficulty: 3,
    timeMin: 24,
    description: "Tube cathodique : déviation entre les plaques puis jusqu'à l'écran — retrouver la formule générale Y = eEL(D+L/2)/mv₀².",
    xpReward: 100,
  },
  {
    id: 'newton-19',
    number: 19,
    tier: 3,
    title: 'Le canon à électrons',
    notion: 'Type Bac',
    difficulty: 3,
    timeMin: 20,
    description: "Accélération d'un électron depuis le repos (U=250 V) : vitesse de sortie par la cinématique ET par bilan d'énergie.",
    xpReward: 100,
  },
  // ── TIER 4 — Défis ◆ ─────────────────────────────────────────────────────
  {
    id: 'newton-20',
    number: 20,
    tier: 4,
    title: "Deux façons d'atteindre la cible",
    notion: 'Défi',
    difficulty: 4,
    timeMin: 25,
    description: 'v₀=20 m/s, cible à 30 m : deux angles de tir possibles (tir tendu / tir en cloche) — cas limite à 45 m.',
    xpReward: 150,
  },
  {
    id: 'newton-21',
    number: 21,
    tier: 4,
    title: "L'influence de la hauteur de lancement",
    notion: 'Défi',
    difficulty: 4,
    timeMin: 30,
    description: "Lanceur de poids (h=2 m, v₀=13 m/s) : portée à α=45° vs α=42° — l'angle optimal n'est plus 45° quand h>0.",
    xpReward: 150,
  },
];

// ─── Module : Mouvement dans un champ de gravitation ───────────────────────
const GRAVITATION_LEVELS: ModuleLevel[] = [
  // ── TIER 0 — QCM ─────────────────────────────────────────────────────────
  {
    id: 'gravitation-qcm',
    number: 0,
    tier: 0,
    title: 'QCM Flash',
    notion: 'Tout le cours',
    difficulty: 0,
    timeMin: 12,
    description: '10 questions pour vérifier que le cours est en place avant de passer aux exercices.',
    xpReward: 30,
  },
  // ── TIER 1 — Automatismes ★ ───────────────────────────────────────────────
  {
    id: 'gravitation-1',
    number: 1,
    tier: 1,
    title: 'Force Soleil / Terre',
    notion: 'Gravitation universelle',
    difficulty: 1,
    timeMin: 6,
    description: 'Appliquer F = G·mₜM_S/d² pour l\'attraction Soleil-Terre : ≈ 3,5×10²² N.',
    xpReward: 40,
  },
  {
    id: 'gravitation-2',
    number: 2,
    tier: 1,
    title: 'Ordre de grandeur',
    notion: 'Gravitation universelle',
    difficulty: 1,
    timeMin: 6,
    description: 'Force entre deux personnes de 70 kg : ≈ 3,3×10⁻⁷ N, totalement imperceptible.',
    xpReward: 40,
  },
  {
    id: 'gravitation-3',
    number: 3,
    tier: 1,
    title: 'Forces réciproques',
    notion: 'Vecteurs & 3ᵉ loi de Newton',
    difficulty: 1,
    timeMin: 7,
    description: 'Schématiser F(T/L) et F(L/T) : opposées, de même valeur (3ᵉ loi de Newton).',
    xpReward: 40,
  },
  {
    id: 'gravitation-4',
    number: 4,
    tier: 1,
    title: 'Pesanteur sur Mars',
    notion: 'Champ de gravitation',
    difficulty: 1,
    timeMin: 6,
    description: 'Calculer g = G·M/R² à la surface de Mars : ≈ 3,7 N·kg⁻¹.',
    xpReward: 40,
  },
  {
    id: 'gravitation-5',
    number: 5,
    tier: 1,
    title: 'Vitesse d\'un satellite',
    notion: 'Mouvement circulaire',
    difficulty: 1,
    timeMin: 6,
    description: 'Appliquer v = √(Gmₜ/r) pour r = 2,0×10⁷ m : ≈ 4,5 km·s⁻¹.',
    xpReward: 40,
  },
  // ── TIER 2 — Méthodes ★★ ─────────────────────────────────────────────────
  {
    id: 'gravitation-6',
    number: 6,
    tier: 2,
    title: 'Champ en altitude',
    notion: 'Champ de gravitation',
    difficulty: 2,
    timeMin: 8,
    description: 'Champ terrestre à h = 400 km : g ≈ 8,7 N·kg⁻¹, l\'altitude le diminue.',
    xpReward: 70,
  },
  {
    id: 'gravitation-7',
    number: 7,
    tier: 2,
    title: 'Poids & masse',
    notion: 'Lien avec le poids',
    difficulty: 2,
    timeMin: 8,
    description: 'Poids d\'un astronaute sur la Lune (130 N) et sur Terre (785 N) : la masse ne change pas.',
    xpReward: 70,
  },
  {
    id: 'gravitation-8',
    number: 8,
    tier: 2,
    title: 'Période de révolution',
    notion: 'Mouvement circulaire',
    difficulty: 2,
    timeMin: 8,
    description: 'T = 2πr/v pour le satellite à r = 2,0×10⁷ m : ≈ 7,8 h.',
    xpReward: 70,
  },
  {
    id: 'gravitation-9',
    number: 9,
    tier: 2,
    title: 'Vitesse de la Lune',
    notion: 'Mouvement circulaire',
    difficulty: 2,
    timeMin: 7,
    description: 'Vitesse orbitale de la Lune (r = 3,84×10⁸ m) : ≈ 1,0 km·s⁻¹.',
    xpReward: 70,
  },
  {
    id: 'gravitation-10',
    number: 10,
    tier: 2,
    title: 'Loi des aires',
    notion: 'Lois de Kepler',
    difficulty: 2,
    timeMin: 7,
    description: 'Vitesse d\'une comète : maximale au périhélie, minimale à l\'aphélie (2ᵉ loi).',
    xpReward: 70,
  },
  {
    id: 'gravitation-11',
    number: 11,
    tier: 2,
    title: 'Constante de Kepler',
    notion: '3ᵉ loi de Kepler',
    difficulty: 2,
    timeMin: 7,
    description: 'Calculer T²/r³ = 4π²/(Gmₜ) pour les satellites terrestres : ≈ 9,9×10⁻¹⁴ SI.',
    xpReward: 70,
  },
  // ── TIER 3 — Approfondissement ★★★ ───────────────────────────────────────
  {
    id: 'gravitation-12',
    number: 12,
    tier: 3,
    title: 'Comparaison de périodes',
    notion: '3ᵉ loi de Kepler',
    difficulty: 3,
    timeMin: 9,
    description: 'Rapport T_B/T_A quand r_B = 2r_A : T ∝ r^(3/2) donne 2√2 ≈ 2,8.',
    xpReward: 100,
  },
  {
    id: 'gravitation-13',
    number: 13,
    tier: 3,
    title: 'Satellite géostationnaire',
    notion: 'Satellites',
    difficulty: 3,
    timeMin: 12,
    description: 'Isoler r dans la 3ᵉ loi avec T = 86 164 s : r ≈ 4,22×10⁷ m, altitude ≈ 35 800 km.',
    xpReward: 100,
  },
  {
    id: 'gravitation-14',
    number: 14,
    tier: 3,
    title: 'Masse de Jupiter',
    notion: 'Masse d\'un astre',
    difficulty: 3,
    timeMin: 12,
    description: '« Peser » Jupiter à partir de l\'orbite de Io : M_J = 4π²r³/(GT²) ≈ 1,9×10²⁷ kg.',
    xpReward: 100,
  },
  {
    id: 'gravitation-15',
    number: 15,
    tier: 3,
    title: 'Établir la vitesse orbitale',
    notion: 'Mouvement circulaire',
    difficulty: 3,
    timeMin: 12,
    description: '2ᵉ loi de Newton → accélération centripète → v = √(Gmₜ/r), indépendante de la masse.',
    xpReward: 100,
  },
  // ── TIER 4 — Sujets type bac ◆ ───────────────────────────────────────────
  {
    id: 'gravitation-16',
    number: 16,
    tier: 4,
    title: 'Bac — Satellite d\'observation',
    notion: 'Étude complète',
    difficulty: 4,
    timeMin: 20,
    description: 'Orbite à h = 800 km : rayon, vitesse (7,5 km·s⁻¹), période (101 min), non géostationnaire.',
    xpReward: 150,
  },
  {
    id: 'gravitation-17',
    number: 17,
    tier: 4,
    title: 'Bac — Masse de Jupiter',
    notion: '3ᵉ loi de Kepler',
    difficulty: 4,
    timeMin: 18,
    description: '3ᵉ loi appliquée à Io, expression et valeur de M_J, comparaison à la valeur tabulée.',
    xpReward: 150,
  },
  {
    id: 'gravitation-18',
    number: 18,
    tier: 4,
    title: 'Bac — Kepler & période de Mars',
    notion: 'Lois de Kepler',
    difficulty: 4,
    timeMin: 20,
    description: 'Constante de Kepler du système solaire, période de Mars ≈ 685 jours, comparaison au réel.',
    xpReward: 150,
  },
];

// ─── Module : Énergie mécanique ────────────────────────────────────────────
const ENERGIE_LEVELS: ModuleLevel[] = [
  // ── TIER 0 — QCM ─────────────────────────────────────────────────────────
  {
    id: 'energie-qcm',
    number: 0,
    tier: 0,
    title: 'QCM Flash',
    notion: 'Tout le cours',
    difficulty: 0,
    timeMin: 12,
    description: '10 questions pour vérifier que le cours est en place avant de passer aux exercices.',
    xpReward: 30,
  },
  // ── TIER 1 — Automatismes ★ ───────────────────────────────────────────────
  {
    id: 'energie-1',
    number: 1,
    tier: 1,
    title: 'Travail d\'une force horizontale',
    notion: 'Travail d\'une force',
    difficulty: 1,
    timeMin: 6,
    description: 'W = F×d×cos 0° pour une force de 120 N sur 15 m : 1,8×10³ J (moteur).',
    xpReward: 40,
  },
  {
    id: 'energie-2',
    number: 2,
    tier: 1,
    title: 'Travail d\'une force inclinée',
    notion: 'Travail d\'une force',
    difficulty: 1,
    timeMin: 6,
    description: 'W = F×d×cos α pour une force de 80 N inclinée de 40° sur 12 m : ≈ 735 J.',
    xpReward: 40,
  },
  {
    id: 'energie-3',
    number: 3,
    tier: 1,
    title: 'Travail du poids — descente',
    notion: 'Travail du poids',
    difficulty: 1,
    timeMin: 6,
    description: 'W(P) = mgh pour une descente de 5,0 m (3,0 kg) : ≈ 147 J (moteur).',
    xpReward: 40,
  },
  {
    id: 'energie-4',
    number: 4,
    tier: 1,
    title: 'Travail du poids — montée',
    notion: 'Travail du poids',
    difficulty: 1,
    timeMin: 6,
    description: 'W(P) = −mgh en montée : ≈ −392 J, travail résistant.',
    xpReward: 40,
  },
  {
    id: 'energie-5',
    number: 5,
    tier: 1,
    title: 'Calcul d\'énergie cinétique',
    notion: 'Énergie cinétique',
    difficulty: 1,
    timeMin: 5,
    description: 'Ec = ½mv² pour une voiture de 1200 kg à 20 m·s⁻¹ : 2,4×10⁵ J.',
    xpReward: 40,
  },
  {
    id: 'energie-6',
    number: 6,
    tier: 1,
    title: 'Calcul d\'énergie mécanique',
    notion: 'Énergie mécanique',
    difficulty: 1,
    timeMin: 6,
    description: 'Em = ½mv² + mgz pour un objet de 2,0 kg à 10 m et 5,0 m·s⁻¹ : ≈ 221 J.',
    xpReward: 40,
  },
  // ── TIER 2 — Méthodes ★★ ─────────────────────────────────────────────────
  {
    id: 'energie-7',
    number: 7,
    tier: 2,
    title: 'Force perpendiculaire',
    notion: 'Travail d\'une force',
    difficulty: 2,
    timeMin: 6,
    description: 'La réaction normale, perpendiculaire au déplacement (α = 90°), ne travaille pas.',
    xpReward: 70,
  },
  {
    id: 'energie-8',
    number: 8,
    tier: 2,
    title: 'Poids sur un plan incliné',
    notion: 'Travail du poids',
    difficulty: 2,
    timeMin: 7,
    description: 'W(P) = mgh ≈ 196 J : indépendant de la longueur du plan, seule la dénivellation compte.',
    xpReward: 70,
  },
  {
    id: 'energie-9',
    number: 9,
    tier: 2,
    title: 'TEC — chute libre',
    notion: 'Théorème de l\'énergie cinétique',
    difficulty: 2,
    timeMin: 7,
    description: 'Appliquer le TEC à une chute de 20 m : v = √(2gh) ≈ 19,8 m·s⁻¹.',
    xpReward: 70,
  },
  {
    id: 'energie-10',
    number: 10,
    tier: 2,
    title: 'Toboggan sans frottement',
    notion: 'Conservation de l\'énergie',
    difficulty: 2,
    timeMin: 7,
    description: 'Conservation de Em sur un toboggan de 3,0 m : v = √(2gh) ≈ 7,7 m·s⁻¹.',
    xpReward: 70,
  },
  {
    id: 'energie-11',
    number: 11,
    tier: 2,
    title: 'Pendule',
    notion: 'Conservation de l\'énergie',
    difficulty: 2,
    timeMin: 7,
    description: 'Vitesse au point bas d\'un pendule lâché de 0,50 m : v = √(2gh) ≈ 3,1 m·s⁻¹.',
    xpReward: 70,
  },
  {
    id: 'energie-12',
    number: 12,
    tier: 2,
    title: 'Arrêt par frottement',
    notion: 'Frottements',
    difficulty: 2,
    timeMin: 8,
    description: 'TEC pour un palet qui s\'arrête après 9,0 m : force de frottement f = 8,0 N.',
    xpReward: 70,
  },
  // ── TIER 3 — Approfondissement ★★★ ───────────────────────────────────────
  {
    id: 'energie-13',
    number: 13,
    tier: 3,
    title: 'Force de freinage',
    notion: 'Théorème de l\'énergie cinétique',
    difficulty: 3,
    timeMin: 9,
    description: 'TEC pour une voiture qui s\'arrête sur 75 m : force de freinage 6,0×10³ N.',
    xpReward: 100,
  },
  {
    id: 'energie-14',
    number: 14,
    tier: 3,
    title: 'Descente avec frottements',
    notion: 'Frottements',
    difficulty: 3,
    timeMin: 10,
    description: 'Bilan Ec = mgh − fL sur un plan : v ≈ 6,8 m·s⁻¹ (vs 8,9 sans frottement).',
    xpReward: 100,
  },
  {
    id: 'energie-15',
    number: 15,
    tier: 3,
    title: 'Énergie dissipée',
    notion: 'Frottements',
    difficulty: 3,
    timeMin: 9,
    description: 'Perte d\'énergie mécanique d\'un skieur : |ΔEm| = mgh − ½mv² ≈ 1,2×10⁴ J.',
    xpReward: 100,
  },
  // ── TIER 4 — Sujets type bac ◆ ───────────────────────────────────────────
  {
    id: 'energie-16',
    number: 16,
    tier: 4,
    title: 'Bac — Chute & TEC',
    notion: 'Théorème de l\'énergie cinétique',
    difficulty: 4,
    timeMin: 18,
    description: 'Bilan des forces, vitesse au sol par TEC, vérification Ec = mgh pour une bille de 100 g.',
    xpReward: 150,
  },
  {
    id: 'energie-17',
    number: 17,
    tier: 4,
    title: 'Bac — Plan incliné avec frottements',
    notion: 'Bilan énergétique',
    difficulty: 4,
    timeMin: 20,
    description: 'Ec en bas, mgh, énergie dissipée (13,4 J) et force de frottement moyenne (4,5 N).',
    xpReward: 150,
  },
  {
    id: 'energie-18',
    number: 18,
    tier: 4,
    title: 'Bac — Conservation & hauteur',
    notion: 'Conservation de l\'énergie',
    difficulty: 4,
    timeMin: 18,
    description: 'Conservation de Em pour trouver la hauteur de départ H : H = h + v²/(2g) ≈ 0,60 m.',
    xpReward: 150,
  },
];

// ─── Module : Bilans thermiques ────────────────────────────────────────────
const BILANS_LEVELS: ModuleLevel[] = [
  // ── TIER 0 — QCM ─────────────────────────────────────────────────────────
  {
    id: 'bilans-qcm',
    number: 0,
    tier: 0,
    title: 'QCM Flash',
    notion: 'Tout le cours',
    difficulty: 0,
    timeMin: 12,
    description: '10 questions pour vérifier que le cours est en place avant de passer aux exercices.',
    xpReward: 30,
  },
  // ── TIER 1 — Automatismes ★ ───────────────────────────────────────────────
  {
    id: 'bilans-1',
    number: 1,
    tier: 1,
    title: 'Calcul de ΔU',
    notion: 'Premier principe',
    difficulty: 1,
    timeMin: 5,
    description: 'ΔU = W + Q pour Q = +30 kJ et W = +5 kJ : +35 kJ (l\'énergie interne augmente).',
    xpReward: 40,
  },
  {
    id: 'bilans-2',
    number: 2,
    tier: 1,
    title: 'Conventions de signe',
    notion: 'Premier principe',
    difficulty: 1,
    timeMin: 5,
    description: 'Chaleur cédée (−200 J), travail reçu (+150 J) : ΔU = −50 J.',
    xpReward: 40,
  },
  {
    id: 'bilans-3',
    number: 3,
    tier: 1,
    title: 'Chauffer de l\'eau',
    notion: 'Capacité thermique',
    difficulty: 1,
    timeMin: 5,
    description: 'Q = mcΔT pour 2,0 kg d\'eau de 15 à 65 °C : ≈ 418 kJ.',
    xpReward: 40,
  },
  {
    id: 'bilans-4',
    number: 4,
    tier: 1,
    title: 'Flux thermique',
    notion: 'Flux thermique',
    difficulty: 1,
    timeMin: 5,
    description: 'Φ = Q/Δt pour 1,8×10⁶ J en 1,0 h : 500 W.',
    xpReward: 40,
  },
  // ── TIER 2 — Méthodes ★★ ─────────────────────────────────────────────────
  {
    id: 'bilans-5',
    number: 5,
    tier: 2,
    title: 'Bloc qui refroidit',
    notion: 'Premier principe',
    difficulty: 2,
    timeMin: 6,
    description: 'Un bloc qui se refroidit cède de l\'énergie : Q < 0, ΔU < 0, la température baisse.',
    xpReward: 70,
  },
  {
    id: 'bilans-6',
    number: 6,
    tier: 2,
    title: 'Autre matériau (fer)',
    notion: 'Capacité thermique',
    difficulty: 2,
    timeMin: 6,
    description: 'Q = mcΔT pour 500 g de fer de 20 à 120 °C : 22,5 kJ.',
    xpReward: 70,
  },
  {
    id: 'bilans-7',
    number: 7,
    tier: 2,
    title: 'Capacité thermique C',
    notion: 'Capacité thermique',
    difficulty: 2,
    timeMin: 7,
    description: 'C = mc = 2700 J·K⁻¹ pour 3,0 kg d\'aluminium, puis Q = CΔT ≈ 1,08×10⁵ J.',
    xpReward: 70,
  },
  {
    id: 'bilans-8',
    number: 8,
    tier: 2,
    title: 'Température finale',
    notion: 'Capacité thermique',
    difficulty: 2,
    timeMin: 7,
    description: 'ΔT = Q/(mc) ≈ 12 K pour 50 kJ à 1,0 kg d\'eau : Tf ≈ 32 °C.',
    xpReward: 70,
  },
  {
    id: 'bilans-9',
    number: 9,
    tier: 2,
    title: 'Mélange d\'eaux',
    notion: 'Équilibre thermique',
    difficulty: 2,
    timeMin: 7,
    description: 'Système isolé : Teq = (m₁T₁ + m₂T₂)/(m₁+m₂) = 34 °C.',
    xpReward: 70,
  },
  {
    id: 'bilans-10',
    number: 10,
    tier: 2,
    title: 'Résistance thermique',
    notion: 'Résistance thermique',
    difficulty: 2,
    timeMin: 6,
    description: 'Rth = e/(λS) pour un mur de 0,25 m : ≈ 0,014 K·W⁻¹.',
    xpReward: 70,
  },
  {
    id: 'bilans-11',
    number: 11,
    tier: 2,
    title: 'Flux à travers un mur',
    notion: 'Flux thermique',
    difficulty: 2,
    timeMin: 6,
    description: 'Φ = ΔT/Rth pour ΔT = 18 K : ≈ 1,3×10³ W.',
    xpReward: 70,
  },
  {
    id: 'bilans-12',
    number: 12,
    tier: 2,
    title: 'Chauffe-eau',
    notion: 'Capacité thermique',
    difficulty: 2,
    timeMin: 7,
    description: 'Q = mcΔT pour 150 L d\'eau de 15 à 55 °C : ≈ 25,1 MJ.',
    xpReward: 70,
  },
  // ── TIER 3 — Approfondissement ★★★ ───────────────────────────────────────
  {
    id: 'bilans-13',
    number: 13,
    tier: 3,
    title: 'Calorimétrie (fer + eau)',
    notion: 'Équilibre thermique',
    difficulty: 3,
    timeMin: 10,
    description: 'Fer à 200 °C dans de l\'eau à 20 °C : Teq = 101 600/4270 ≈ 23,8 °C.',
    xpReward: 100,
  },
  {
    id: 'bilans-14',
    number: 14,
    tier: 3,
    title: 'Comparaison d\'isolants',
    notion: 'Résistance thermique',
    difficulty: 3,
    timeMin: 9,
    description: 'Rth ∝ 1/λ : la laine de verre isole ≈ 38 fois mieux que le béton.',
    xpReward: 100,
  },
  {
    id: 'bilans-15',
    number: 15,
    tier: 3,
    title: 'Puissance thermique',
    notion: 'Flux thermique',
    difficulty: 3,
    timeMin: 9,
    description: 'P = Q/Δt pour le chauffe-eau en 2,0 h : ≈ 3,5 kW.',
    xpReward: 100,
  },
  {
    id: 'bilans-16',
    number: 16,
    tier: 3,
    title: 'Pertes d\'une maison',
    notion: 'Bilan thermique',
    difficulty: 3,
    timeMin: 10,
    description: 'Φ = ΔT/Rth = 4,0 kW puis E = ΦΔt ≈ 346 MJ sur 24 h.',
    xpReward: 100,
  },
  // ── TIER 4 — Sujets type bac ◆ ───────────────────────────────────────────
  {
    id: 'bilans-17',
    number: 17,
    tier: 4,
    title: 'Bac — Calorimétrie cuivre + eau',
    notion: 'Équilibre thermique',
    difficulty: 4,
    timeMin: 18,
    description: 'Bilan du système isolé, température d\'équilibre (≈ 21,9 °C) et vérification des signes.',
    xpReward: 150,
  },
  {
    id: 'bilans-18',
    number: 18,
    tier: 4,
    title: 'Bac — Isolation d\'un mur',
    notion: 'Résistance thermique',
    difficulty: 4,
    timeMin: 20,
    description: 'Résistance et flux d\'un mur, énergie perdue en 24 h, ajout d\'un isolant en série (flux ÷ 8,5).',
    xpReward: 150,
  },
  {
    id: 'bilans-19',
    number: 19,
    tier: 4,
    title: 'Bac — Chauffage d\'une piscine',
    notion: 'Bilan thermique',
    difficulty: 4,
    timeMin: 18,
    description: 'Énergie pour chauffer 30 m³ d\'eau (≈ 1003 MJ), durée avec une PAC de 15 kW (≈ 18,6 h), pertes.',
    xpReward: 150,
  },
];

// ─── Module : Ondes mécaniques ─────────────────────────────────────────────
const ONDES_LEVELS: ModuleLevel[] = [
  // ── TIER 0 — QCM ─────────────────────────────────────────────────────────
  {
    id: 'ondes-qcm',
    number: 0,
    tier: 0,
    title: 'QCM Flash',
    notion: 'Tout le cours',
    difficulty: 0,
    timeMin: 12,
    description: '10 questions pour vérifier que le cours est en place avant de passer aux exercices.',
    xpReward: 30,
  },
  // ── TIER 1 — Automatismes ★ ───────────────────────────────────────────────
  {
    id: 'ondes-1',
    number: 1,
    tier: 1,
    title: 'Transversale ou longitudinale',
    notion: 'Nature des ondes',
    difficulty: 1,
    timeMin: 5,
    description: 'Classer son, vague, corde et ressort en ondes transversales ou longitudinales.',
    xpReward: 40,
  },
  {
    id: 'ondes-2',
    number: 2,
    tier: 1,
    title: 'Transport d\'énergie',
    notion: 'Onde progressive',
    difficulty: 1,
    timeMin: 5,
    description: 'Une onde transporte de l\'énergie, pas de matière (le bouchon oscille sur place).',
    xpReward: 40,
  },
  {
    id: 'ondes-3',
    number: 3,
    tier: 1,
    title: 'Fréquence f = 1/T',
    notion: 'Période & fréquence',
    difficulty: 1,
    timeMin: 4,
    description: 'f = 1/T pour une période de 4,0 ms : 250 Hz.',
    xpReward: 40,
  },
  {
    id: 'ondes-4',
    number: 4,
    tier: 1,
    title: 'Longueur d\'onde λ = v/f',
    notion: 'Relation fondamentale',
    difficulty: 1,
    timeMin: 5,
    description: 'λ = v/f pour un son de 680 Hz dans l\'air : 0,50 m.',
    xpReward: 40,
  },
  {
    id: 'ondes-5',
    number: 5,
    tier: 1,
    title: 'Onde sur une corde',
    notion: 'Relation fondamentale',
    difficulty: 1,
    timeMin: 5,
    description: 'λ = v/f pour une corde à 15 m·s⁻¹ et 25 Hz : 0,60 m.',
    xpReward: 40,
  },
  {
    id: 'ondes-6',
    number: 6,
    tier: 1,
    title: 'Distance de l\'orage',
    notion: 'Retard',
    difficulty: 1,
    timeMin: 5,
    description: 'd = v·τ pour un tonnerre entendu 6,0 s après l\'éclair : ≈ 2,0 km.',
    xpReward: 40,
  },
  // ── TIER 2 — Méthodes ★★ ─────────────────────────────────────────────────
  {
    id: 'ondes-7',
    number: 7,
    tier: 2,
    title: 'De quoi dépend la célérité',
    notion: 'Célérité',
    difficulty: 2,
    timeMin: 6,
    description: 'La célérité dépend du milieu, pas de la fréquence imposée par la source.',
    xpReward: 70,
  },
  {
    id: 'ondes-8',
    number: 8,
    tier: 2,
    title: 'Son audible ?',
    notion: 'Ondes sonores',
    difficulty: 2,
    timeMin: 6,
    description: 'f = 1/T = 400 Hz pour T = 2,5 ms : compris entre 20 Hz et 20 kHz, donc audible.',
    xpReward: 70,
  },
  {
    id: 'ondes-9',
    number: 9,
    tier: 2,
    title: 'Célérité de la houle',
    notion: 'Relation fondamentale',
    difficulty: 2,
    timeMin: 6,
    description: 'v = λ/T pour une houle (λ = 8,0 m, T = 4,0 s) : 2,0 m·s⁻¹.',
    xpReward: 70,
  },
  {
    id: 'ondes-10',
    number: 10,
    tier: 2,
    title: 'Célérité & conversion d\'unités',
    notion: 'Relation fondamentale',
    difficulty: 2,
    timeMin: 6,
    description: 'v = λ/T pour λ = 1,5 m et T = 5,0 ms : 300 m·s⁻¹.',
    xpReward: 70,
  },
  {
    id: 'ondes-11',
    number: 11,
    tier: 2,
    title: 'Retard entre deux capteurs',
    notion: 'Retard',
    difficulty: 2,
    timeMin: 6,
    description: 'τ = d/v pour deux micros distants de 1,7 m : 5,0 ms.',
    xpReward: 70,
  },
  {
    id: 'ondes-12',
    number: 12,
    tier: 2,
    title: 'Écho sur une falaise',
    notion: 'Écho & mesures',
    difficulty: 2,
    timeMin: 6,
    description: 'd = v·Δt/2 pour un écho revenant après 1,2 s : ≈ 204 m.',
    xpReward: 70,
  },
  {
    id: 'ondes-13',
    number: 13,
    tier: 2,
    title: 'Sonar',
    notion: 'Écho & mesures',
    difficulty: 2,
    timeMin: 6,
    description: 'd = v·Δt/2 pour un écho de fond après 0,080 s dans l\'eau : 60 m.',
    xpReward: 70,
  },
  // ── TIER 3 — Approfondissement ★★★ ───────────────────────────────────────
  {
    id: 'ondes-14',
    number: 14,
    tier: 3,
    title: 'Déphasage entre deux points',
    notion: 'Retard & phase',
    difficulty: 3,
    timeMin: 9,
    description: 'τ = d/v = 0,0625 s ; d = λ/2 → les deux points sont en opposition de phase.',
    xpReward: 100,
  },
  {
    id: 'ondes-15',
    number: 15,
    tier: 3,
    title: 'Échographie',
    notion: 'Écho & mesures',
    difficulty: 3,
    timeMin: 9,
    description: 'd = v·Δt/2 pour un écho après 40 µs dans les tissus : ≈ 3,1 cm.',
    xpReward: 100,
  },
  // ── TIER 4 — Sujets type bac ◆ ───────────────────────────────────────────
  {
    id: 'ondes-16',
    number: 16,
    tier: 4,
    title: 'Bac — Sonar',
    notion: 'Écho & mesures',
    difficulty: 4,
    timeMin: 18,
    description: 'Aller-retour, profondeur (90 m) puis comparaison d\'un second écho (150 m, +60 m).',
    xpReward: 150,
  },
  {
    id: 'ondes-17',
    number: 17,
    tier: 4,
    title: 'Bac — Onde sur une corde',
    notion: 'Relation fondamentale',
    difficulty: 4,
    timeMin: 18,
    description: 'Période, longueur d\'onde puis retard et phase de deux points (opposition de phase).',
    xpReward: 150,
  },
  {
    id: 'ondes-18',
    number: 18,
    tier: 4,
    title: 'Bac — Orage',
    notion: 'Retard',
    difficulty: 4,
    timeMin: 16,
    description: 'Décalage lumière/son, distance (1,5 km) et rapprochement de l\'orage (1,0 km).',
    xpReward: 150,
  },
];

export const PHYSICS_MODULES: PhysicsModule[] = [
  {
    id: 'phys-newton',
    subject: 'Physique',
    level: 'Terminale',
    title: 'Newton & champ uniforme',
    subtitle: 'Lois de Newton · Projectile · Champ électrique',
    accentHsl: '205 85% 60%',
    pdfCours:      '/modules/phys-newton/cours.pdf',
    pdfFiche:      '/modules/phys-newton/fiche.pdf',
    pdfExercices:  '/modules/phys-newton/exercices.pdf',
    levels: NEWTON_LEVELS,
  },
  {
    id: 'phys-gravitation',
    subject: 'Physique',
    level: 'Terminale',
    title: 'Mouvement dans un champ de gravitation',
    subtitle: 'Gravitation · Champ · Kepler · Satellites',
    accentHsl: '205 85% 60%',
    pdfCours:     null,
    pdfFiche:     null,
    pdfExercices: null,
    levels: GRAVITATION_LEVELS,
  },
  {
    id: 'phys-energie',
    subject: 'Physique',
    level: 'Terminale',
    title: 'Énergie mécanique',
    subtitle: 'Travail · Énergie cinétique · TEC · Conservation',
    accentHsl: '205 85% 60%',
    pdfCours:     null,
    pdfFiche:     null,
    pdfExercices: null,
    levels: ENERGIE_LEVELS,
  },
  {
    id: 'phys-bilans',
    subject: 'Physique',
    level: 'Terminale',
    title: 'Bilans thermiques',
    subtitle: 'Énergie interne · Premier principe · Transferts · Flux & résistance',
    accentHsl: '205 85% 60%',
    pdfCours:     null,
    pdfFiche:     null,
    pdfExercices: null,
    levels: BILANS_LEVELS,
  },
  {
    id: 'phys-ondes',
    subject: 'Physique',
    level: 'Terminale',
    title: 'Ondes mécaniques',
    subtitle: 'Onde progressive · Célérité & retard · λ = v·T · Ondes sonores',
    accentHsl: '205 85% 60%',
    pdfCours:     null,
    pdfFiche:     null,
    pdfExercices: null,
    levels: ONDES_LEVELS,
  },
];

// ─── Module 2 : Suites & Récurrence ────────────────────────────────────────
const SUITES_LEVELS: ModuleLevel[] = [
  // ── TIER 0 — QCM ─────────────────────────────────────────────────────────
  {
    id: 'suites-qcm',
    number: 0,
    tier: 0,
    title: 'QCM Flash',
    notion: 'Tout le cours',
    difficulty: 0,
    timeMin: 12,
    description: '12 questions pour vérifier les fondamentaux avant de passer aux exercices.',
    xpReward: 30,
  },
  // ── TIER 1 — Automatismes ★ ───────────────────────────────────────────────
  {
    id: 'suites-1',
    number: 1,
    tier: 1,
    title: 'Divisibilité par récurrence',
    notion: 'Récurrence',
    difficulty: 1,
    timeMin: 8,
    description: 'Démontrer que 4ⁿ − 1 est un multiple de 3 par un raisonnement par récurrence simple.',
    xpReward: 40,
  },
  {
    id: 'suites-2',
    number: 2,
    tier: 1,
    title: 'Encadrement par récurrence',
    notion: 'Récurrence',
    difficulty: 1,
    timeMin: 8,
    description: 'Montrer que 0 ≤ uₙ ≤ 2 pour uₙ₊₁ = √(uₙ + 2) et en déduire la stabilité de la suite.',
    xpReward: 40,
  },
  {
    id: 'suites-3',
    number: 3,
    tier: 1,
    title: 'Forme explicite par récurrence',
    notion: 'Récurrence',
    difficulty: 1,
    timeMin: 8,
    description: 'Prouver par récurrence que uₙ = 70×1,14ⁿ + 50 pour u₀ = 120 et uₙ₊₁ = 1,14uₙ − 7.',
    xpReward: 40,
  },
  {
    id: 'suites-4',
    number: 4,
    tier: 1,
    title: 'Somme des entiers',
    notion: 'Récurrence',
    difficulty: 1,
    timeMin: 7,
    description: 'Démontrer que Σk (k=1 à n) = n(n+1)/2 par récurrence.',
    xpReward: 40,
  },
  {
    id: 'suites-5',
    number: 5,
    tier: 1,
    title: 'Définition de la limite',
    notion: 'Convergence',
    difficulty: 1,
    timeMin: 8,
    description: 'Déterminer N tel que uₙ = 4/n soit arbitrairement proche de 0 ; montrer la convergence.',
    xpReward: 40,
  },
  {
    id: 'suites-6',
    number: 6,
    tier: 1,
    title: 'Gendarmes simples',
    notion: 'Gendarmes',
    difficulty: 1,
    timeMin: 7,
    description: 'Encadrer eₙ = 1/(n+5) puis appliquer le théorème des gendarmes.',
    xpReward: 40,
  },
  {
    id: 'suites-7',
    number: 7,
    tier: 1,
    title: 'Gendarmes trigonométriques',
    notion: 'Gendarmes',
    difficulty: 1,
    timeMin: 8,
    description: 'Encadrer wₙ = (cos n + 2 sin n)/n² et en déduire sa limite.',
    xpReward: 40,
  },
  // ── TIER 2 — Méthodes ★★ ─────────────────────────────────────────────────
  {
    id: 'suites-8',
    number: 8,
    tier: 2,
    title: 'Monotonie par récurrence',
    notion: 'Récurrence',
    difficulty: 2,
    timeMin: 12,
    description: 'Pour wₙ₊₁ = √(7wₙ) : montrer 0 ≤ wₙ ≤ wₙ₊₁ ≤ 7 par récurrence puis conclure sur la convergence.',
    xpReward: 70,
  },
  {
    id: 'suites-9',
    number: 9,
    tier: 2,
    title: 'Somme des carrés',
    notion: 'Récurrence',
    difficulty: 2,
    timeMin: 12,
    description: 'Démontrer que Σk² = n(n+1)(2n+1)/6 par récurrence.',
    xpReward: 70,
  },
  {
    id: 'suites-10',
    number: 10,
    tier: 2,
    title: 'Divisibilité de 9ⁿ − 1',
    notion: 'Récurrence',
    difficulty: 2,
    timeMin: 10,
    description: 'Montrer que 9ⁿ − 1 est divisible par 8 pour tout n ∈ ℕ.',
    xpReward: 70,
  },
  {
    id: 'suites-11',
    number: 11,
    tier: 2,
    title: 'Inégalité de Bernoulli',
    notion: 'Récurrence',
    difficulty: 2,
    timeMin: 10,
    description: 'Démontrer (1+a)ⁿ ≥ 1 + na pour tout a ≥ 0 et n ∈ ℕ.',
    xpReward: 70,
  },
  {
    id: 'suites-12',
    number: 12,
    tier: 2,
    title: 'Divergence vers +∞',
    notion: 'Divergence',
    difficulty: 2,
    timeMin: 10,
    description: 'Déterminer N tel que √n > 2020, puis montrer que uₙ = √n diverge vers +∞.',
    xpReward: 70,
  },
  {
    id: 'suites-13',
    number: 13,
    tier: 2,
    title: 'Croissance comparée — eⁿ',
    notion: 'Divergence',
    difficulty: 2,
    timeMin: 12,
    description: 'Montrer eⁿ ≥ n+1 par récurrence, puis en déduire que (eⁿ) diverge vers +∞.',
    xpReward: 70,
  },
  {
    id: 'suites-14',
    number: 14,
    tier: 2,
    title: 'Suite géométrique et somme',
    notion: 'Limite',
    difficulty: 2,
    timeMin: 12,
    description: 'Pour uₙ = (2/3)ⁿ : déterminer la limite, exprimer Sₙ sous forme close, calculer lim Sₙ.',
    xpReward: 70,
  },
  // ── TIER 3 — Type Bac ★★★ ────────────────────────────────────────────────
  {
    id: 'suites-15',
    number: 15,
    tier: 3,
    title: 'Formes indéterminées',
    notion: 'Limites',
    difficulty: 3,
    timeMin: 15,
    description: 'Calculer lim(n²−2n+5) et lim(3n+1)/(n²+2n−8) en levant les formes indéterminées.',
    xpReward: 100,
  },
  {
    id: 'suites-16',
    number: 16,
    tier: 3,
    title: 'Suite récurrente complète',
    notion: 'Suite récurrente',
    difficulty: 3,
    timeMin: 20,
    description: 'Pour uₙ₊₁ = √(uₙ+2) : étudier la monotonie, justifier la convergence, déterminer la limite.',
    xpReward: 100,
  },
  {
    id: 'suites-17',
    number: 17,
    tier: 3,
    title: 'Arithmético-géométrique',
    notion: 'Type Bac',
    difficulty: 3,
    timeMin: 22,
    description: 'uₙ₊₁ = 0,5uₙ + 3 : montrer que vₙ = uₙ − 6 est géométrique, exprimer uₙ, lim uₙ et Sₙ.',
    xpReward: 100,
  },
  {
    id: 'suites-18',
    number: 18,
    tier: 3,
    title: 'Étude complète + algorithme',
    notion: 'Type Bac',
    difficulty: 3,
    timeMin: 25,
    description: 'uₙ₊₁ = √(2uₙ+3) : encadrement par récurrence, monotonie, convergence, limite et algorithme de seuil.',
    xpReward: 100,
  },
  // ── TIER 4 — Défis ◆ ─────────────────────────────────────────────────────
  {
    id: 'suites-19',
    number: 19,
    tier: 4,
    title: 'Suite homographique',
    notion: 'Défi',
    difficulty: 4,
    timeMin: 25,
    description: 'uₙ₊₁ = uₙ/(1+uₙ) : montrer que vₙ = 1/uₙ est arithmétique, exprimer uₙ et déterminer la limite.',
    xpReward: 150,
  },
  {
    id: 'suites-20',
    number: 20,
    tier: 4,
    title: 'Encadrement par somme',
    notion: 'Défi',
    difficulty: 4,
    timeMin: 28,
    description: 'uₙ = Σ 1/(n²+k) : encadrer uₙ entre n/(n²+n) et n/(n²+1), puis appliquer les gendarmes.',
    xpReward: 150,
  },
  {
    id: 'suites-21',
    number: 21,
    tier: 4,
    title: 'Récurrence double + suite auxiliaire',
    notion: 'Défi',
    difficulty: 4,
    timeMin: 30,
    description: 'uₙ₊₂ = (uₙ₊₁+uₙ)/2 : poser vₙ = uₙ₊₁−uₙ, montrer géométrique, télescoper et trouver lim uₙ.',
    xpReward: 150,
  },
];

// ─── Module 3 : Les fonctions ──────────────────────────────────────────────
const FONCTIONS_LEVELS: ModuleLevel[] = [
  // ── TIER 0 — QCM ─────────────────────────────────────────────────────────
  {
    id: 'fonctions-qcm',
    number: 0,
    tier: 0,
    title: 'QCM Flash',
    notion: 'Tout le cours',
    difficulty: 0,
    timeMin: 15,
    description: '12 questions pour vérifier que le cours est en place avant de passer aux exercices.',
    xpReward: 30,
  },
  // ── TIER 1 — Automatismes ★ ───────────────────────────────────────────────
  {
    id: 'fonctions-1',
    number: 1,
    tier: 1,
    title: 'Limite en +∞ par définition',
    notion: 'Limites',
    difficulty: 1,
    timeMin: 7,
    description: 'Montrer rigoureusement que lim(1/x) = 0 en +∞ à l\'aide de la définition ε, B.',
    xpReward: 40,
  },
  {
    id: 'fonctions-2',
    number: 2,
    tier: 1,
    title: 'Gendarmes — cos(x)/x',
    notion: 'Gendarmes',
    difficulty: 1,
    timeMin: 6,
    description: 'Encadrer cos(x)/x entre ±1/x et conclure par le théorème des gendarmes.',
    xpReward: 40,
  },
  {
    id: 'fonctions-3',
    number: 3,
    tier: 1,
    title: 'Gendarmes — 4 + cos(x)/x²',
    notion: 'Gendarmes',
    difficulty: 1,
    timeMin: 7,
    description: 'Encadrer h(x) = 4 + cos(x)/x² et déterminer sa limite en ±∞.',
    xpReward: 40,
  },
  {
    id: 'fonctions-4',
    number: 4,
    tier: 1,
    title: 'Formes indéterminées',
    notion: 'Limites',
    difficulty: 1,
    timeMin: 8,
    description: 'Lever ∞/∞ par factorisation et ∞−∞ par quantité conjuguée.',
    xpReward: 40,
  },
  {
    id: 'fonctions-5',
    number: 5,
    tier: 1,
    title: 'Asymptotes de (2x+1)/(x−1)',
    notion: 'Asymptotes',
    difficulty: 1,
    timeMin: 8,
    description: 'Calculer les limites en ±∞ et en x = 1 pour identifier les asymptotes.',
    xpReward: 40,
  },
  {
    id: 'fonctions-6',
    number: 6,
    tier: 1,
    title: 'Croissance comparée — eˣ − x³',
    notion: 'Croissances comparées',
    difficulty: 1,
    timeMin: 7,
    description: 'Utiliser eˣ ≫ x³ pour déterminer la limite de eˣ − x³ en +∞.',
    xpReward: 40,
  },
  {
    id: 'fonctions-7',
    number: 7,
    tier: 1,
    title: 'Limites avec eˣ',
    notion: 'Exponentielle',
    difficulty: 1,
    timeMin: 8,
    description: 'Calculer lim eˣ/(x²+1) en +∞ et lim xeˣ en −∞ par croissances comparées.',
    xpReward: 40,
  },
  // ── TIER 2 — Méthodes ★★ ─────────────────────────────────────────────────
  {
    id: 'fonctions-8',
    number: 8,
    tier: 2,
    title: 'Équation de tangente',
    notion: 'Dérivation',
    difficulty: 2,
    timeMin: 8,
    description: 'Déterminer les tangentes à y = x³ en x = 1 et à y = eˣ en x = 0.',
    xpReward: 70,
  },
  {
    id: 'fonctions-9',
    number: 9,
    tier: 2,
    title: 'Dérivées composées',
    notion: 'Dérivation',
    difficulty: 2,
    timeMin: 9,
    description: 'Dériver e^(−x²), √(x²+1) et (2x−1)⁴ par la règle de dérivation en chaîne.',
    xpReward: 70,
  },
  {
    id: 'fonctions-10',
    number: 10,
    tier: 2,
    title: 'Tableau de variations — quotient',
    notion: 'Variations',
    difficulty: 2,
    timeMin: 10,
    description: 'Étudier g(x) = −2x/(x²+1) : limites, dérivée, tableau complet avec extrema.',
    xpReward: 70,
  },
  {
    id: 'fonctions-11',
    number: 11,
    tier: 2,
    title: 'Tableau de variations — cubique',
    notion: 'Variations',
    difficulty: 2,
    timeMin: 10,
    description: 'Étudier f(x) = x³ − 3x² + x − 1 : limites, signe de f\', tableau de variations.',
    xpReward: 70,
  },
  {
    id: 'fonctions-12',
    number: 12,
    tier: 2,
    title: 'Convexité — xeˣ',
    notion: 'Convexité',
    difficulty: 2,
    timeMin: 9,
    description: 'Calculer f\'\'(x) pour f(x) = xeˣ et en déduire les intervalles de convexité.',
    xpReward: 70,
  },
  {
    id: 'fonctions-13',
    number: 13,
    tier: 2,
    title: 'Convexité — x⁴ − 6x²',
    notion: 'Convexité',
    difficulty: 2,
    timeMin: 10,
    description: 'Déterminer les intervalles de convexité/concavité et les points d\'inflexion de x⁴ − 6x².',
    xpReward: 70,
  },
  {
    id: 'fonctions-14',
    number: 14,
    tier: 2,
    title: 'Inégalité eˣ ≥ x + 1',
    notion: 'Convexité',
    difficulty: 2,
    timeMin: 9,
    description: 'Démontrer que eˣ ≥ x + 1 pour tout x réel en utilisant la convexité de eˣ.',
    xpReward: 70,
  },
  // ── TIER 3 — Type Bac ★★★ ────────────────────────────────────────────────
  {
    id: 'fonctions-15',
    number: 15,
    tier: 3,
    title: 'Continuité sans dérivabilité',
    notion: 'Continuité',
    difficulty: 3,
    timeMin: 10,
    description: 'Montrer que |x| est continue mais non dérivable en 0 (taux d\'accroissement).',
    xpReward: 100,
  },
  {
    id: 'fonctions-16',
    number: 16,
    tier: 3,
    title: 'TVI — existence d\'une solution',
    notion: 'TVI',
    difficulty: 3,
    timeMin: 10,
    description: 'Prouver qu\'il existe c ∈ [−3, 0] tel que f(c) = −1 pour f(x) = x³ + 4x² + 4x.',
    xpReward: 100,
  },
  {
    id: 'fonctions-17',
    number: 17,
    tier: 3,
    title: 'Unique solution — x³ + x − 1 = 0',
    notion: 'TVI + Unicité',
    difficulty: 3,
    timeMin: 12,
    description: 'Montrer que x³ + x − 1 = 0 a une unique solution α et l\'encadrer à 0,1 près.',
    xpReward: 100,
  },
  {
    id: 'fonctions-18',
    number: 18,
    tier: 3,
    title: 'Trois solutions — x³ − 3x + 1 = 0',
    notion: 'TVI',
    difficulty: 3,
    timeMin: 15,
    description: 'Déterminer le nombre exact de solutions de x³ − 3x + 1 = 0 à l\'aide du tableau de variations.',
    xpReward: 100,
  },
  // ── TIER 4 — Défis ◆ ─────────────────────────────────────────────────────
  {
    id: 'fonctions-19',
    number: 19,
    tier: 4,
    title: 'Étude complète — (x+1)e^(−x)',
    notion: 'Type Bac',
    difficulty: 4,
    timeMin: 20,
    description: 'Limites, variations, tangente en 0 et point d\'inflexion de f(x) = (x+1)e^(−x).',
    xpReward: 150,
  },
  {
    id: 'fonctions-20',
    number: 20,
    tier: 4,
    title: 'Étude complète — xeˣ',
    notion: 'Type Bac',
    difficulty: 4,
    timeMin: 20,
    description: 'Limites, variations (minimum), convexité et point d\'inflexion de f(x) = xeˣ.',
    xpReward: 150,
  },
  {
    id: 'fonctions-21',
    number: 21,
    tier: 4,
    title: 'TVI + Encadrement — x³ + x − 3 = 0',
    notion: 'Type Bac',
    difficulty: 4,
    timeMin: 18,
    description: 'Prouver l\'unicité de la racine de x³ + x − 3 = 0 et l\'encadrer à 0,1 près.',
    xpReward: 150,
  },
];

// ─── Module 4 : Logarithme népérien ────────────────────────────────────────
const LOGARITHME_LEVELS: ModuleLevel[] = [
  // ── TIER 0 — QCM ─────────────────────────────────────────────────────────
  {
    id: 'logarithme-qcm',
    number: 0,
    tier: 0,
    title: 'QCM Flash',
    notion: 'Tout le cours',
    difficulty: 0,
    timeMin: 12,
    description: '12 questions pour vérifier que le cours ln est en place avant de passer aux exercices.',
    xpReward: 30,
  },
  // ── TIER 1 — Automatismes ★ ───────────────────────────────────────────────
  {
    id: 'logarithme-1',
    number: 1,
    tier: 1,
    title: 'Exprimer avec ln 2 et ln 3',
    notion: 'Propriétés algébriques',
    difficulty: 1,
    timeMin: 6,
    description: 'Décomposer ln 6, ln(8/3), ln√12 et ln(1/9) en combinaisons de ln 2 et ln 3.',
    xpReward: 40,
  },
  {
    id: 'logarithme-2',
    number: 2,
    tier: 1,
    title: 'Simplifications',
    notion: 'Propriétés algébriques',
    difficulty: 1,
    timeMin: 5,
    description: 'Simplifier ln(e²)+ln(1/e), e^(2ln3) et ln(eˣ·e⁻²) en utilisant les relations fondamentales.',
    xpReward: 40,
  },
  {
    id: 'logarithme-3',
    number: 3,
    tier: 1,
    title: 'Démonstration d\'identité',
    notion: 'Propriétés algébriques',
    difficulty: 1,
    timeMin: 5,
    description: 'Montrer que ln(x)+ln(1+1/x)=ln(x+1) pour tout x>0 en factorisant.',
    xpReward: 40,
  },
  {
    id: 'logarithme-4',
    number: 4,
    tier: 1,
    title: 'Équations avec ln et exp',
    notion: 'Équations',
    difficulty: 1,
    timeMin: 8,
    description: 'Résoudre eˣ=5, ln x=−2 et ln(3x−6)=ln(12+x) en vérifiant les domaines.',
    xpReward: 40,
  },
  {
    id: 'logarithme-5',
    number: 5,
    tier: 1,
    title: 'Inéquations avec ln et exp',
    notion: 'Inéquations',
    difficulty: 1,
    timeMin: 8,
    description: 'Résoudre e^(5x)≤2, ln(3x+1)>0 et ln(2x)≤ln(6−x) en précisant les domaines.',
    xpReward: 40,
  },
  {
    id: 'logarithme-6',
    number: 6,
    tier: 1,
    title: 'Transformation et équation',
    notion: 'Équations',
    difficulty: 1,
    timeMin: 10,
    description: 'Démontrer x+ln(1+3e⁻ˣ)=ln(3+eˣ) puis résoudre x+ln(1+3e⁻ˣ)=2.',
    xpReward: 40,
  },
  // ── TIER 2 — Méthodes ★★ ─────────────────────────────────────────────────
  {
    id: 'logarithme-7',
    number: 7,
    tier: 2,
    title: 'Limites en 0⁺ et +∞',
    notion: 'Limites',
    difficulty: 2,
    timeMin: 12,
    description: 'Étudier les limites de f(x)=ln x−x² et g(x)=x²−3x−ln x en 0⁺ et en +∞.',
    xpReward: 60,
  },
  {
    id: 'logarithme-8',
    number: 8,
    tier: 2,
    title: 'Croissances comparées',
    notion: 'Croissances comparées',
    difficulty: 2,
    timeMin: 10,
    description: 'Calculer lim(ln x)/(x+1), lim x²ln x et lim(x−ln x) par la hiérarchie ln x≪x≪eˣ.',
    xpReward: 60,
  },
  {
    id: 'logarithme-9',
    number: 9,
    tier: 2,
    title: 'Forme indéterminée ln/ln',
    notion: 'Limites',
    difficulty: 2,
    timeMin: 12,
    description: 'Décomposer ln(x²+1) pour calculer lim_{x→+∞} ln(x²+1)/ln x.',
    xpReward: 60,
  },
  {
    id: 'logarithme-10',
    number: 10,
    tier: 2,
    title: 'Dérivées de ln composé',
    notion: 'Dérivation',
    difficulty: 2,
    timeMin: 10,
    description: 'Dériver ln(x²+1), ln(2x−1) et x ln x en appliquant (ln u)\'=u\'/u.',
    xpReward: 60,
  },
  {
    id: 'logarithme-11',
    number: 11,
    tier: 2,
    title: 'Dérivée de (ln x)/x',
    notion: 'Dérivation',
    difficulty: 2,
    timeMin: 8,
    description: 'Calculer f\'(x) pour f(x)=(ln x)/x par la règle du quotient.',
    xpReward: 60,
  },
  {
    id: 'logarithme-12',
    number: 12,
    tier: 2,
    title: 'Dérivée de (ln x)²−ln x',
    notion: 'Dérivation',
    difficulty: 2,
    timeMin: 8,
    description: 'Justifier h\'(x)=(2ln x−1)/x pour h(x)=(ln x)²−ln x par dérivation de composée.',
    xpReward: 60,
  },
  // ── TIER 3 — Type Bac ★★★ ────────────────────────────────────────────────
  {
    id: 'logarithme-13',
    number: 13,
    tier: 3,
    title: 'Étude de x−ln x',
    notion: 'Type Bac',
    difficulty: 3,
    timeMin: 20,
    description: 'Étude complète de f(x)=x−ln x : limites, variations, minimum — et preuve que x>ln x pour tout x>0.',
    xpReward: 100,
  },
  {
    id: 'logarithme-14',
    number: 14,
    tier: 3,
    title: 'Étude de (ln x)/x',
    notion: 'Type Bac',
    difficulty: 3,
    timeMin: 20,
    description: 'Étude complète de f(x)=(ln x)/x : limites, asymptote, maximum en x=e.',
    xpReward: 100,
  },
  {
    id: 'logarithme-15',
    number: 15,
    tier: 3,
    title: 'Étude de (ln x)²−ln x',
    notion: 'Type Bac',
    difficulty: 3,
    timeMin: 22,
    description: 'Étude complète de h(x)=(ln x)²−ln x : minimum en √e, résolution de h(x)=0.',
    xpReward: 100,
  },
  {
    id: 'logarithme-16',
    number: 16,
    tier: 3,
    title: 'Étude de x²−2 ln x',
    notion: 'Type Bac',
    difficulty: 3,
    timeMin: 18,
    description: 'Étude complète de f(x)=x²−2ln x sur ]0,+∞[ : minimum f(1)=1.',
    xpReward: 100,
  },
  {
    id: 'logarithme-17',
    number: 17,
    tier: 3,
    title: 'TVI — ln x+x−3=0',
    notion: 'Type Bac',
    difficulty: 3,
    timeMin: 18,
    description: 'Prouver l\'existence et l\'unicité de la solution de ln x+x−3=0, puis l\'encadrer à 0,1.',
    xpReward: 100,
  },
];

// ─── Module : Probabilités & loi binomiale ─────────────────────────────────
const PROBABILITES_LEVELS: ModuleLevel[] = [
  // ── TIER 0 — QCM ─────────────────────────────────────────────────────────
  {
    id: 'probabilites-qcm',
    number: 0,
    tier: 0,
    title: 'QCM Flash',
    notion: 'Tout le cours',
    difficulty: 0,
    timeMin: 12,
    description: '10 questions pour vérifier que le cours est en place avant de passer aux exercices.',
    xpReward: 30,
  },
  // ── TIER 1 — Automatismes ★ ───────────────────────────────────────────────
  {
    id: 'probabilites-1',
    number: 1,
    tier: 1,
    title: 'Sac de jetons',
    notion: 'Conditionnelles',
    difficulty: 1,
    timeMin: 8,
    description: 'Calculer P(R), P(R∩G) et les deux conditionnelles P_R(G) et P_G(R) — et voir qu\'elles diffèrent.',
    xpReward: 40,
  },
  {
    id: 'probabilites-2',
    number: 2,
    tier: 1,
    title: 'Arbre pondéré',
    notion: 'Arbre & probas totales',
    difficulty: 1,
    timeMin: 8,
    description: 'Construire l\'arbre à partir de P(A), P_A(B), P_Ā(B), puis calculer P(B) et remonter à P_B(A).',
    xpReward: 40,
  },
  {
    id: 'probabilites-3',
    number: 3,
    tier: 1,
    title: 'Deux dés indépendants ?',
    notion: 'Indépendance',
    difficulty: 1,
    timeMin: 7,
    description: 'Vérifier par le calcul si « premier dé = 6 » et « somme = 7 » sont indépendants.',
    xpReward: 40,
  },
  {
    id: 'probabilites-4',
    number: 4,
    tier: 1,
    title: 'Loi, espérance, variance',
    notion: 'Variables aléatoires',
    difficulty: 1,
    timeMin: 8,
    description: 'Vérifier une loi de probabilité puis calculer E(X), V(X) et σ(X) avec König-Huygens.',
    xpReward: 40,
  },
  {
    id: 'probabilites-5',
    number: 5,
    tier: 1,
    title: 'Calculs binomiaux — B(20 ; 0,3)',
    notion: 'Loi binomiale',
    difficulty: 1,
    timeMin: 10,
    description: 'P(X=6), P(X≤6), P(X≥8), P(4≤X≤8) à la calculatrice, puis E(X), V(X), σ(X).',
    xpReward: 40,
  },
  // ── TIER 2 — Méthodes ★★ ─────────────────────────────────────────────────
  {
    id: 'probabilites-6',
    number: 6,
    tier: 2,
    title: 'Deux machines',
    notion: 'Probas totales',
    difficulty: 2,
    timeMin: 10,
    description: 'Probabilités totales sur un arbre à deux machines, puis inversion : P_D(M1).',
    xpReward: 70,
  },
  {
    id: 'probabilites-7',
    number: 7,
    tier: 2,
    title: 'Indépendance & complémentaire',
    notion: 'Indépendance',
    difficulty: 2,
    timeMin: 8,
    description: 'P(A∩B), P(A∪B), et montrer que l\'indépendance se propage au complémentaire B̄.',
    xpReward: 70,
  },
  {
    id: 'probabilites-8',
    number: 8,
    tier: 2,
    title: 'Jeu à la roue',
    notion: 'Espérance',
    difficulty: 2,
    timeMin: 10,
    description: 'Loi du gain algébrique d\'une roue à 8 secteurs, espérance, et verdict : jeu favorable ?',
    xpReward: 70,
  },
  {
    id: 'probabilites-9',
    number: 9,
    tier: 2,
    title: 'Transformation affine Y = 3X − 5',
    notion: 'Linéarité',
    difficulty: 2,
    timeMin: 7,
    description: 'Appliquer E(aX+b) = aE(X)+b et V(aX+b) = a²V(X) sans se tromper sur le b.',
    xpReward: 70,
  },
  {
    id: 'probabilites-10',
    number: 10,
    tier: 2,
    title: 'Au moins un défectueux',
    notion: 'Loi binomiale',
    difficulty: 2,
    timeMin: 9,
    description: 'Justifier le modèle binomial B(12 ; 0,05) puis calculer P(X≥1) par l\'événement contraire.',
    xpReward: 70,
  },
  {
    id: 'probabilites-11',
    number: 11,
    tier: 2,
    title: 'Moyenne empirique',
    notion: 'Échantillon',
    difficulty: 2,
    timeMin: 8,
    description: 'E, V et σ de la moyenne M₁₀₀ d\'un échantillon de 100 variables indépendantes.',
    xpReward: 70,
  },
  {
    id: 'probabilites-12',
    number: 12,
    tier: 2,
    title: 'Inégalité de Bienaymé-Tchebychev',
    notion: 'Concentration',
    difficulty: 2,
    timeMin: 7,
    description: 'Majorer P(|X−50| ≥ 10) à partir de la seule variance, sans connaître la loi.',
    xpReward: 70,
  },
  // ── TIER 3 — Approfondissement ★★★ ───────────────────────────────────────
  {
    id: 'probabilites-13',
    number: 13,
    tier: 3,
    title: 'Dépistage — inversion de Bayes',
    notion: 'Fréquence de base',
    difficulty: 3,
    timeMin: 12,
    description: 'Un test fiable à 98% mais un positif n\'est malade qu\'à 25% : calculer et expliquer le paradoxe.',
    xpReward: 100,
  },
  {
    id: 'probabilites-14',
    number: 14,
    tier: 3,
    title: 'Somme de variables',
    notion: 'Variance d\'une somme',
    difficulty: 3,
    timeMin: 10,
    description: 'E(S) et V(S) pour S = X+Y indépendantes — et pourquoi V(S) est incalculable sans indépendance.',
    xpReward: 100,
  },
  {
    id: 'probabilites-15',
    number: 15,
    tier: 3,
    title: 'Seuil de lancers francs',
    notion: 'Seuil avec ln',
    difficulty: 3,
    timeMin: 12,
    description: 'Trouver le plus petit n tel que 1−(0,8)ⁿ > 0,99 en passant au logarithme.',
    xpReward: 100,
  },
  {
    id: 'probabilites-16',
    number: 16,
    tier: 3,
    title: 'Dimensionner un échantillon',
    notion: 'Concentration',
    difficulty: 3,
    timeMin: 12,
    description: 'Combien de lancers pour estimer p à 0,05 près avec un risque ≤ 5% ? (n = 2000)',
    xpReward: 100,
  },
  // ── TIER 4 — Sujets type bac ◆ ───────────────────────────────────────────
  {
    id: 'probabilites-17',
    number: 17,
    tier: 4,
    title: 'Bac — Contrôle qualité',
    notion: 'Arbre + binomiale',
    difficulty: 4,
    timeMin: 20,
    description: 'Deux chaînes de production : arbre, probas totales, inversion, puis binomiale sur 15 composants.',
    xpReward: 150,
  },
  {
    id: 'probabilites-18',
    number: 18,
    tier: 4,
    title: 'Bac — QCM au hasard',
    notion: 'Loi binomiale',
    difficulty: 4,
    timeMin: 20,
    description: '30 questions à 4 choix au hasard : B(30 ; 0,25), calculs de probabilités et interprétation.',
    xpReward: 150,
  },
  {
    id: 'probabilites-19',
    number: 19,
    tier: 4,
    title: 'Bac — Pièce truquée & LGN',
    notion: 'Concentration · LGN',
    difficulty: 4,
    timeMin: 22,
    description: 'Majorer V(Mₙ) par 1/(4n), appliquer la concentration et interpréter la loi des grands nombres.',
    xpReward: 150,
  },
  {
    id: 'probabilites-20',
    number: 20,
    tier: 4,
    title: 'Bac — Jeu & binomiale',
    notion: 'VA + binomiale',
    difficulty: 4,
    timeMin: 20,
    description: 'Roue à 12 secteurs : loi du gain, espérance, écart-type, puis Y ~ B(20 ; 1/6) sur 20 parties.',
    xpReward: 150,
  },
];

// ─── Module : Géométrie dans l'espace ──────────────────────────────────────
const GEOMETRIE_LEVELS: ModuleLevel[] = [
  // ── TIER 0 — QCM ─────────────────────────────────────────────────────────
  {
    id: 'geometrie-qcm',
    number: 0,
    tier: 0,
    title: 'QCM Flash',
    notion: 'Tout le cours',
    difficulty: 0,
    timeMin: 12,
    description: '10 questions pour vérifier que le cours est en place avant de passer aux exercices.',
    xpReward: 30,
  },
  // ── TIER 1 — Automatismes ★ ───────────────────────────────────────────────
  {
    id: 'geometrie-1',
    number: 1,
    tier: 1,
    title: 'Colinéarité',
    notion: 'Vecteurs',
    difficulty: 1,
    timeMin: 6,
    description: 'Reconnaître deux vecteurs colinéaires en exhibant le coefficient k tel que u = kv.',
    xpReward: 40,
  },
  {
    id: 'geometrie-2',
    number: 2,
    tier: 1,
    title: 'Distance entre deux points',
    notion: 'Coordonnées',
    difficulty: 1,
    timeMin: 6,
    description: 'Appliquer la formule AB = √((xB−xA)² + (yB−yA)² + (zB−zA)²) en repère orthonormé.',
    xpReward: 40,
  },
  {
    id: 'geometrie-3',
    number: 3,
    tier: 1,
    title: 'Milieu d\'un segment',
    notion: 'Coordonnées',
    difficulty: 1,
    timeMin: 5,
    description: 'Calculer les coordonnées du milieu par moyennes des coordonnées.',
    xpReward: 40,
  },
  {
    id: 'geometrie-4',
    number: 4,
    tier: 1,
    title: 'Représentation paramétrique',
    notion: 'Droites',
    difficulty: 1,
    timeMin: 7,
    description: 'Écrire la représentation paramétrique d\'une droite à partir d\'un point et d\'un vecteur directeur.',
    xpReward: 40,
  },
  {
    id: 'geometrie-5',
    number: 5,
    tier: 1,
    title: 'Orthogonalité de deux vecteurs',
    notion: 'Produit scalaire',
    difficulty: 1,
    timeMin: 6,
    description: 'Tester l\'orthogonalité par le produit scalaire analytique xx\' + yy\' + zz\' = 0.',
    xpReward: 40,
  },
  {
    id: 'geometrie-6',
    number: 6,
    tier: 1,
    title: 'Équation cartésienne d\'un plan',
    notion: 'Plans',
    difficulty: 1,
    timeMin: 8,
    description: 'Écrire ax+by+cz+d = 0 à partir du vecteur normal, puis trouver d avec le point A.',
    xpReward: 40,
  },
  // ── TIER 2 — Méthodes ★★ ─────────────────────────────────────────────────
  {
    id: 'geometrie-7',
    number: 7,
    tier: 2,
    title: 'Coplanarité',
    notion: 'Vecteurs',
    difficulty: 2,
    timeMin: 9,
    description: 'Exprimer w comme combinaison au + bv en résolvant le système sur les coordonnées.',
    xpReward: 70,
  },
  {
    id: 'geometrie-8',
    number: 8,
    tier: 2,
    title: 'Alignement de trois points',
    notion: 'Vecteurs',
    difficulty: 2,
    timeMin: 8,
    description: 'Montrer que AB et AC sont colinéaires pour conclure à l\'alignement.',
    xpReward: 70,
  },
  {
    id: 'geometrie-9',
    number: 9,
    tier: 2,
    title: 'Nature d\'un triangle',
    notion: 'Distances',
    difficulty: 2,
    timeMin: 9,
    description: 'Calculer les trois longueurs de côtés et identifier un triangle équilatéral.',
    xpReward: 70,
  },
  {
    id: 'geometrie-10',
    number: 10,
    tier: 2,
    title: 'Appartenance à une droite',
    notion: 'Droites',
    difficulty: 2,
    timeMin: 9,
    description: 'Vérifier qu\'un même t satisfait les trois équations paramétriques — ou aboutir à une incompatibilité.',
    xpReward: 70,
  },
  {
    id: 'geometrie-11',
    number: 11,
    tier: 2,
    title: 'Angle entre deux vecteurs',
    notion: 'Produit scalaire',
    difficulty: 2,
    timeMin: 8,
    description: 'Calculer cos(u,v) = u·v / (||u|| ||v||) et en déduire l\'angle de 60°.',
    xpReward: 70,
  },
  {
    id: 'geometrie-12',
    number: 12,
    tier: 2,
    title: 'Vecteur orthogonal à deux vecteurs',
    notion: 'Produit scalaire',
    difficulty: 2,
    timeMin: 9,
    description: 'Résoudre le système n·u = 0 et n·v = 0 pour construire un vecteur normal.',
    xpReward: 70,
  },
  {
    id: 'geometrie-13',
    number: 13,
    tier: 2,
    title: 'Plan passant par trois points',
    notion: 'Plans',
    difficulty: 2,
    timeMin: 12,
    description: 'Trouver un vecteur normal à (ABC) puis en déduire l\'équation cartésienne du plan.',
    xpReward: 70,
  },
  {
    id: 'geometrie-14',
    number: 14,
    tier: 2,
    title: 'Position relative de deux plans',
    notion: 'Positions relatives',
    difficulty: 2,
    timeMin: 8,
    description: 'Comparer les vecteurs normaux : colinéaires mais équations non proportionnelles → strictement parallèles.',
    xpReward: 70,
  },
  {
    id: 'geometrie-15',
    number: 15,
    tier: 2,
    title: 'Position droite / plan',
    notion: 'Positions relatives',
    difficulty: 2,
    timeMin: 9,
    description: 'Tester u·n = 0 puis l\'appartenance d\'un point pour conclure au parallélisme strict.',
    xpReward: 70,
  },
  {
    id: 'geometrie-16',
    number: 16,
    tier: 2,
    title: 'Intersection droite / plan',
    notion: 'Intersections',
    difficulty: 2,
    timeMin: 10,
    description: 'Substituer la paramétrique dans l\'équation du plan, résoudre en t, reporter le point.',
    xpReward: 70,
  },
  // ── TIER 3 — Approfondissement ★★★ ───────────────────────────────────────
  {
    id: 'geometrie-17',
    number: 17,
    tier: 3,
    title: 'Distance & projeté orthogonal',
    notion: 'Distances',
    difficulty: 3,
    timeMin: 14,
    description: 'Distance point-plan par la formule, coordonnées du projeté H, et vérification MH = d(M,P).',
    xpReward: 100,
  },
  // ── TIER 4 — Sujets type bac ◆ ───────────────────────────────────────────
  {
    id: 'geometrie-18',
    number: 18,
    tier: 4,
    title: 'Bac — Le cube',
    notion: 'Plan + distance',
    difficulty: 4,
    timeMin: 20,
    description: 'Dans le cube unité : montrer que AG est normal au plan (BDE), équation du plan, distance de G.',
    xpReward: 150,
  },
  {
    id: 'geometrie-19',
    number: 19,
    tier: 4,
    title: 'Bac — Droite & plan',
    notion: 'Intersection + distance',
    difficulty: 4,
    timeMin: 20,
    description: 'Paramétrique, preuve que D et (P) sont sécants, point d\'intersection (7;−3;5), distance de O.',
    xpReward: 150,
  },
  {
    id: 'geometrie-20',
    number: 20,
    tier: 4,
    title: 'Bac — Le tétraèdre',
    notion: 'Orthogonalité + plan',
    difficulty: 4,
    timeMin: 22,
    description: 'Tétraèdre trirectangle : orthogonalité deux à deux, triangle équilatéral, plan (BCD), distance de A.',
    xpReward: 150,
  },
];

// ─── Module : Primitives & intégrales ──────────────────────────────────────
const PRIMITIVES_LEVELS: ModuleLevel[] = [
  // ── TIER 0 — QCM ─────────────────────────────────────────────────────────
  {
    id: 'primitives-qcm',
    number: 0,
    tier: 0,
    title: 'QCM Flash',
    notion: 'Tout le cours',
    difficulty: 0,
    timeMin: 12,
    description: '10 questions pour vérifier que le cours est en place avant de passer aux exercices.',
    xpReward: 30,
  },
  // ── TIER 1 — Automatismes ★ ───────────────────────────────────────────────
  {
    id: 'primitives-1',
    number: 1,
    tier: 1,
    title: 'Primitive d\'un polynôme',
    notion: 'Primitives usuelles',
    difficulty: 1,
    timeMin: 6,
    description: 'Primitiver 3x²−4x+5 terme à terme, puis vérifier en dérivant.',
    xpReward: 40,
  },
  {
    id: 'primitives-2',
    number: 2,
    tier: 1,
    title: 'Primitives de puissances',
    notion: 'Primitives usuelles',
    difficulty: 1,
    timeMin: 7,
    description: 'Réécrire 1/x² et 2/√x en puissances pour trouver −1/x + 4√x.',
    xpReward: 40,
  },
  {
    id: 'primitives-3',
    number: 3,
    tier: 1,
    title: 'Primitive avec condition F(1) = 5',
    notion: 'Condition initiale',
    difficulty: 1,
    timeMin: 7,
    description: 'Forme générale 2x³−2x+k, puis fixer k avec la condition F(1) = 5.',
    xpReward: 40,
  },
  {
    id: 'primitives-4',
    number: 4,
    tier: 1,
    title: 'Première intégrale',
    notion: 'Théorème fondamental',
    difficulty: 1,
    timeMin: 5,
    description: 'Calculer ∫ de 1 à 3 de 2x dx avec [x²] = 9 − 1 = 8.',
    xpReward: 40,
  },
  {
    id: 'primitives-5',
    number: 5,
    tier: 1,
    title: 'Intégrale nulle ≠ fonction nulle',
    notion: 'Théorème fondamental',
    difficulty: 1,
    timeMin: 6,
    description: '∫(3x²−1) sur [0;1] vaut 0 : les aires positives et négatives se compensent.',
    xpReward: 40,
  },
  // ── TIER 2 — Méthodes ★★ ─────────────────────────────────────────────────
  {
    id: 'primitives-6',
    number: 6,
    tier: 2,
    title: 'Exponentielle & trigo',
    notion: 'Primitives usuelles',
    difficulty: 2,
    timeMin: 7,
    description: 'Primitiver 2eˣ − 3sin x en combinant les primitives usuelles par linéarité.',
    xpReward: 70,
  },
  {
    id: 'primitives-7',
    number: 7,
    tier: 2,
    title: 'Forme u\'uⁿ',
    notion: 'Formes composées',
    difficulty: 2,
    timeMin: 8,
    description: 'Reconnaître u = x²+3 et u\' = 2x pour primitiver 2x(x²+3)⁴ en u⁵/5.',
    xpReward: 70,
  },
  {
    id: 'primitives-8',
    number: 8,
    tier: 2,
    title: 'Forme u\'/u',
    notion: 'Formes composées',
    difficulty: 2,
    timeMin: 8,
    description: 'Faire apparaître le facteur ½ pour primitiver x/(x²+1) en ½ln(x²+1).',
    xpReward: 70,
  },
  {
    id: 'primitives-9',
    number: 9,
    tier: 2,
    title: 'Forme u\'eᵘ',
    notion: 'Formes composées',
    difficulty: 2,
    timeMin: 8,
    description: 'Reconnaître u = x²−x et u\' = 2x−1 pour primitiver (2x−1)e^(x²−x).',
    xpReward: 70,
  },
  {
    id: 'primitives-10',
    number: 10,
    tier: 2,
    title: 'Primitive avec condition F(0) = 2',
    notion: 'Condition initiale',
    difficulty: 2,
    timeMin: 7,
    description: 'Forme générale eˣ+x+k, puis fixer k = 1 avec la condition F(0) = 2.',
    xpReward: 70,
  },
  {
    id: 'primitives-11',
    number: 11,
    tier: 2,
    title: 'Intégrale et logarithme',
    notion: 'Calcul d\'intégrales',
    difficulty: 2,
    timeMin: 6,
    description: '∫ de 1 à e de 1/x dx = [ln x] = 1 : l\'aire sous l\'hyperbole vaut exactement 1.',
    xpReward: 70,
  },
  {
    id: 'primitives-12',
    number: 12,
    tier: 2,
    title: 'Intégrale d\'une composée',
    notion: 'Calcul d\'intégrales',
    difficulty: 2,
    timeMin: 9,
    description: 'Reconnaître ½u\'eᵘ dans xe^(x²) pour obtenir (e−1)/2.',
    xpReward: 70,
  },
  {
    id: 'primitives-13',
    number: 13,
    tier: 2,
    title: 'Linéarité de l\'intégrale',
    notion: 'Propriétés',
    difficulty: 2,
    timeMin: 7,
    description: 'Calculer ∫(3x²+2eˣ) en séparant les deux morceaux : résultat 2e−1.',
    xpReward: 70,
  },
  {
    id: 'primitives-14',
    number: 14,
    tier: 2,
    title: 'Valeur absolue & Chasles',
    notion: 'Propriétés',
    difficulty: 2,
    timeMin: 9,
    description: 'Découper ∫|x−1| en x = 1 avec la relation de Chasles : ½ + ½ = 1.',
    xpReward: 70,
  },
  {
    id: 'primitives-15',
    number: 15,
    tier: 2,
    title: 'Valeur moyenne',
    notion: 'Valeur moyenne',
    difficulty: 2,
    timeMin: 7,
    description: 'Valeur moyenne de x³ sur [0;2] : μ = ½∫x³ = 2.',
    xpReward: 70,
  },
  {
    id: 'primitives-16',
    number: 16,
    tier: 2,
    title: 'Première IPP',
    notion: 'Intégration par parties',
    difficulty: 2,
    timeMin: 10,
    description: 'Poser u = x+1 et v\' = eˣ pour calculer ∫(x+1)eˣ = e.',
    xpReward: 70,
  },
  // ── TIER 3 — Approfondissement ★★★ ───────────────────────────────────────
  {
    id: 'primitives-17',
    number: 17,
    tier: 3,
    title: 'Forme u\'u² cachée',
    notion: 'Formes composées',
    difficulty: 3,
    timeMin: 9,
    description: 'Voir cos x·sin²x comme u\'u² avec u = sin x : primitive sin³x/3.',
    xpReward: 100,
  },
  {
    id: 'primitives-18',
    number: 18,
    tier: 3,
    title: 'Aire entre deux courbes',
    notion: 'Aires',
    difficulty: 3,
    timeMin: 10,
    description: 'Aire entre y = 2x et y = x² sur [0;2] : ∫(2x−x²) = 4/3 u.a.',
    xpReward: 100,
  },
  {
    id: 'primitives-19',
    number: 19,
    tier: 3,
    title: 'IPP avec logarithme',
    notion: 'Intégration par parties',
    difficulty: 3,
    timeMin: 12,
    description: 'Poser u = ln x et v\' = x pour calculer ∫x ln x = (e²+1)/4.',
    xpReward: 100,
  },
  {
    id: 'primitives-20',
    number: 20,
    tier: 3,
    title: 'IPP trigonométrique',
    notion: 'Intégration par parties',
    difficulty: 3,
    timeMin: 12,
    description: 'Poser u = x et v\' = sin x pour calculer ∫x sin x sur [0;π] = π.',
    xpReward: 100,
  },
  // ── TIER 4 — Sujets type bac ◆ ───────────────────────────────────────────
  {
    id: 'primitives-21',
    number: 21,
    tier: 4,
    title: 'Bac — Primitive & aire',
    notion: 'Primitive + aire',
    difficulty: 4,
    timeMin: 20,
    description: 'Vérifier que (3−x)eˣ primitive (2−x)eˣ, calculer l\'intégrale, le signe, puis l\'aire e²−3.',
    xpReward: 150,
  },
  {
    id: 'primitives-22',
    number: 22,
    tier: 4,
    title: 'Bac — IPP successives',
    notion: 'Intégration par parties',
    difficulty: 4,
    timeMin: 20,
    description: 'Calculer J = ∫xeˣ = 1, exprimer I = ∫x²eˣ en fonction de J, conclure I = e−2.',
    xpReward: 150,
  },
  {
    id: 'primitives-23',
    number: 23,
    tier: 4,
    title: 'Bac — Aire & moyenne',
    notion: 'Aires + valeur moyenne',
    difficulty: 4,
    timeMin: 20,
    description: 'Intersections de −x²+4x et x, aire entre les courbes 9/2, valeur moyenne μ = 3.',
    xpReward: 150,
  },
];

// ─── Module : Fonction exponentielle ───────────────────────────────────────
const EXPONENTIELLE_LEVELS: ModuleLevel[] = [
  // ── TIER 0 — QCM ─────────────────────────────────────────────────────────
  {
    id: 'exponentielle-qcm',
    number: 0,
    tier: 0,
    title: 'QCM Flash',
    notion: 'Tout le cours',
    difficulty: 0,
    timeMin: 12,
    description: '10 questions pour vérifier que le cours est en place avant de passer aux exercices.',
    xpReward: 30,
  },
  // ── TIER 1 — Automatismes ★ ───────────────────────────────────────────────
  {
    id: 'exponentielle-1',
    number: 1,
    tier: 1,
    title: 'Simplifications de base',
    notion: 'Propriétés algébriques',
    difficulty: 1,
    timeMin: 6,
    description: 'Simplifier e³×e⁻¹, e⁵/e² et (e²)³ avec la relation fonctionnelle.',
    xpReward: 40,
  },
  {
    id: 'exponentielle-2',
    number: 2,
    tier: 1,
    title: 'Dérivées de e^u',
    notion: 'Dérivation',
    difficulty: 1,
    timeMin: 7,
    description: 'Appliquer (e^u)\' = u\'e^u sur e^(3x) et e^(−x²).',
    xpReward: 40,
  },
  {
    id: 'exponentielle-3',
    number: 3,
    tier: 1,
    title: 'Équation e^A = e^B',
    notion: 'Équations',
    difficulty: 1,
    timeMin: 5,
    description: 'Résoudre e^(2x) = e^(x+3) en égalant les exposants.',
    xpReward: 40,
  },
  {
    id: 'exponentielle-4',
    number: 4,
    tier: 1,
    title: 'Limite eˣ/x²',
    notion: 'Croissances comparées',
    difficulty: 1,
    timeMin: 5,
    description: 'L\'exponentielle l\'emporte sur toute puissance : limite +∞ en +∞.',
    xpReward: 40,
  },
  // ── TIER 2 — Méthodes ★★ ─────────────────────────────────────────────────
  {
    id: 'exponentielle-5',
    number: 5,
    tier: 2,
    title: 'Écrire sous la forme e^kx',
    notion: 'Propriétés algébriques',
    difficulty: 2,
    timeMin: 8,
    description: 'Regrouper les exposants pour réduire (eˣ×e^2x)/e⁻ˣ et (eˣ)²×e⁻ˣ.',
    xpReward: 70,
  },
  {
    id: 'exponentielle-6',
    number: 6,
    tier: 2,
    title: 'Factorisation e^2x − 1',
    notion: 'Propriétés algébriques',
    difficulty: 2,
    timeMin: 7,
    description: 'Développer (eˣ−1)(eˣ+1) pour retrouver l\'identité remarquable.',
    xpReward: 70,
  },
  {
    id: 'exponentielle-7',
    number: 7,
    tier: 2,
    title: 'Dérivée d\'un produit',
    notion: 'Dérivation',
    difficulty: 2,
    timeMin: 8,
    description: 'Dériver (2x−1)eˣ avec la règle du produit et factoriser par eˣ.',
    xpReward: 70,
  },
  {
    id: 'exponentielle-8',
    number: 8,
    tier: 2,
    title: 'Dérivée d\'un quotient',
    notion: 'Dérivation',
    difficulty: 2,
    timeMin: 8,
    description: 'Dériver eˣ/x avec la règle du quotient : résultat (x−1)eˣ/x².',
    xpReward: 70,
  },
  {
    id: 'exponentielle-9',
    number: 9,
    tier: 2,
    title: 'Dérivée de x²e⁻ˣ',
    notion: 'Dérivation',
    difficulty: 2,
    timeMin: 8,
    description: 'Produit + composée : factoriser le résultat en x(2−x)e⁻ˣ.',
    xpReward: 70,
  },
  {
    id: 'exponentielle-10',
    number: 10,
    tier: 2,
    title: 'Changement de variable X = eˣ',
    notion: 'Équations',
    difficulty: 2,
    timeMin: 10,
    description: 'Résoudre e^2x − 4eˣ + 3 = 0 via X²−4X+3 = 0, puis revenir à x.',
    xpReward: 70,
  },
  {
    id: 'exponentielle-11',
    number: 11,
    tier: 2,
    title: 'Équation e^(x²−1) = 1',
    notion: 'Équations',
    difficulty: 2,
    timeMin: 7,
    description: 'Écrire 1 = e⁰ pour se ramener à x²−1 = 0.',
    xpReward: 70,
  },
  {
    id: 'exponentielle-12',
    number: 12,
    tier: 2,
    title: 'Inéquation e⁻ˣ < e²',
    notion: 'Inéquations',
    difficulty: 2,
    timeMin: 6,
    description: 'Utiliser la stricte croissance pour comparer les exposants.',
    xpReward: 70,
  },
  {
    id: 'exponentielle-13',
    number: 13,
    tier: 2,
    title: 'Limite x²eˣ en −∞',
    notion: 'Croissances comparées',
    difficulty: 2,
    timeMin: 7,
    description: 'Lever la forme 0×∞ par croissances comparées : xⁿeˣ → 0 en −∞.',
    xpReward: 70,
  },
  {
    id: 'exponentielle-14',
    number: 14,
    tier: 2,
    title: 'Limite du taux en 0',
    notion: 'Limites',
    difficulty: 2,
    timeMin: 6,
    description: 'Réécrire (eˣ−1)/(2x) avec la limite de référence (eˣ−1)/x → 1.',
    xpReward: 70,
  },
  {
    id: 'exponentielle-15',
    number: 15,
    tier: 2,
    title: 'Variations de (x−1)eˣ',
    notion: 'Étude de fonctions',
    difficulty: 2,
    timeMin: 10,
    description: 'f\'(x) = xeˣ a le signe de x : minimum en 0 valant −1.',
    xpReward: 70,
  },
  // ── TIER 3 — Approfondissement ★★★ ───────────────────────────────────────
  {
    id: 'exponentielle-16',
    number: 16,
    tier: 3,
    title: 'Forme indéterminée eˣ − x³',
    notion: 'Croissances comparées',
    difficulty: 3,
    timeMin: 10,
    description: 'Factoriser par eˣ et conclure avec x³/eˣ → 0 : limite +∞.',
    xpReward: 100,
  },
  {
    id: 'exponentielle-17',
    number: 17,
    tier: 3,
    title: 'Inégalité eˣ ≥ x + 1',
    notion: 'Étude de fonctions',
    difficulty: 3,
    timeMin: 12,
    description: 'Étudier f(x) = eˣ−x : minimum 1 en 0, d\'où l\'inégalité classique.',
    xpReward: 100,
  },
  {
    id: 'exponentielle-18',
    number: 18,
    tier: 3,
    title: 'Étude complète de xe⁻ˣ',
    notion: 'Étude de fonctions',
    difficulty: 3,
    timeMin: 14,
    description: 'f\' = (1−x)e⁻ˣ, maximum 1/e en x = 1, limites −∞ et 0⁺.',
    xpReward: 100,
  },
  // ── TIER 4 — Sujets type bac ◆ ───────────────────────────────────────────
  {
    id: 'exponentielle-19',
    number: 19,
    tier: 4,
    title: 'Bac — Étude de (x+1)e⁻ˣ',
    notion: 'Étude complète',
    difficulty: 4,
    timeMin: 20,
    description: 'Dérivée −xe⁻ˣ, maximum f(0) = 1, limites, et tangente horizontale y = 1.',
    xpReward: 150,
  },
  {
    id: 'exponentielle-20',
    number: 20,
    tier: 4,
    title: 'Bac — Équation & signe',
    notion: 'Factorisation',
    difficulty: 4,
    timeMin: 18,
    description: 'Factoriser e^2x−3eˣ+2 en (eˣ−1)(eˣ−2), racines 0 et ln 2, tableau de signes.',
    xpReward: 150,
  },
  {
    id: 'exponentielle-21',
    number: 21,
    tier: 4,
    title: 'Bac — Étude & primitive',
    notion: 'Étude + intégrale',
    difficulty: 4,
    timeMin: 20,
    description: 'Minimum de xeˣ en −1, primitive (x−1)eˣ, et ∫xeˣ = 1 sur [0;1].',
    xpReward: 150,
  },
];

// ─── Module : Équations différentielles ────────────────────────────────────
const EQUADIFF_LEVELS: ModuleLevel[] = [
  // ── TIER 0 — QCM ─────────────────────────────────────────────────────────
  {
    id: 'equadiff-qcm',
    number: 0,
    tier: 0,
    title: 'QCM Flash',
    notion: 'Tout le cours',
    difficulty: 0,
    timeMin: 12,
    description: '10 questions pour vérifier que le cours est en place avant de passer aux exercices.',
    xpReward: 30,
  },
  // ── TIER 1 — Automatismes ★ ───────────────────────────────────────────────
  {
    id: 'equadiff-1',
    number: 1,
    tier: 1,
    title: 'Solutions de y\' = ay',
    notion: 'Équation y\' = ay',
    difficulty: 1,
    timeMin: 6,
    description: 'Donner les solutions Ce^ax pour y\'=3y, y\'=−2y et y\'=½y.',
    xpReward: 40,
  },
  {
    id: 'equadiff-2',
    number: 2,
    tier: 1,
    title: 'Vérifier une solution',
    notion: 'Vérification',
    difficulty: 1,
    timeMin: 6,
    description: 'Dériver f(x) = 5e^(−4x) et vérifier qu\'elle satisfait y\' = −4y.',
    xpReward: 40,
  },
  {
    id: 'equadiff-3',
    number: 3,
    tier: 1,
    title: 'Premier problème de Cauchy',
    notion: 'Condition initiale',
    difficulty: 1,
    timeMin: 6,
    description: 'Déterminer la solution de y\' = 2y vérifiant y(0) = 5.',
    xpReward: 40,
  },
  {
    id: 'equadiff-4',
    number: 4,
    tier: 1,
    title: 'Solutions de y\' = ay + b',
    notion: 'Équation y\' = ay + b',
    difficulty: 1,
    timeMin: 6,
    description: 'Appliquer la formule Ce^ax − b/a sur y\' = 2y + 6.',
    xpReward: 40,
  },
  // ── TIER 2 — Méthodes ★★ ─────────────────────────────────────────────────
  {
    id: 'equadiff-5',
    number: 5,
    tier: 2,
    title: 'Mise en forme 2y\' − 6y = 0',
    notion: 'Équation y\' = ay',
    difficulty: 2,
    timeMin: 7,
    description: 'Isoler y\' pour reconnaître y\' = 3y avant de résoudre.',
    xpReward: 70,
  },
  {
    id: 'equadiff-6',
    number: 6,
    tier: 2,
    title: 'Cauchy puis évaluation',
    notion: 'Condition initiale',
    difficulty: 2,
    timeMin: 8,
    description: 'Résoudre y\' = −y avec y(0) = 3, puis calculer y(1) = 3/e.',
    xpReward: 70,
  },
  {
    id: 'equadiff-7',
    number: 7,
    tier: 2,
    title: 'Condition en x₀ ≠ 0',
    notion: 'Condition initiale',
    difficulty: 2,
    timeMin: 9,
    description: 'y\' = ½y avec y(2) = 4 : la condition n\'est plus en 0, C = 4e⁻¹.',
    xpReward: 70,
  },
  {
    id: 'equadiff-8',
    number: 8,
    tier: 2,
    title: 'Solutions & équilibre',
    notion: 'Équation y\' = ay + b',
    difficulty: 2,
    timeMin: 8,
    description: 'Résoudre y\' = −3y + 12 et identifier la solution d\'équilibre y = 4.',
    xpReward: 70,
  },
  {
    id: 'equadiff-9',
    number: 9,
    tier: 2,
    title: 'Solution d\'équilibre',
    notion: 'Équilibre',
    difficulty: 2,
    timeMin: 7,
    description: 'Trouver la solution constante de y\' = 4y − 8 et la vérifier.',
    xpReward: 70,
  },
  {
    id: 'equadiff-10',
    number: 10,
    tier: 2,
    title: 'Résolution complète',
    notion: 'Cauchy y\' = ay + b',
    difficulty: 2,
    timeMin: 9,
    description: 'Résoudre y\' = −2y + 6 avec y(0) = 1 : solution −2e^(−2x) + 3.',
    xpReward: 70,
  },
  {
    id: 'equadiff-11',
    number: 11,
    tier: 2,
    title: 'Refroidissement de Newton',
    notion: 'Modélisation',
    difficulty: 2,
    timeMin: 12,
    description: 'T\' = −0,05(T−20), T(0) = 80 : mise en forme, résolution, T(20) ≈ 42,1°.',
    xpReward: 70,
  },
  // ── TIER 3 — Approfondissement ★★★ ───────────────────────────────────────
  {
    id: 'equadiff-12',
    number: 12,
    tier: 3,
    title: 'Étude en +∞ — divergence',
    notion: 'Comportement asymptotique',
    difficulty: 3,
    timeMin: 10,
    description: 'y\' = y − 2 avec y(0) = 5 : la solution 3eˣ + 2 s\'écarte de l\'équilibre.',
    xpReward: 100,
  },
  {
    id: 'equadiff-13',
    number: 13,
    tier: 3,
    title: 'Convergence vers l\'équilibre',
    notion: 'Comportement asymptotique',
    difficulty: 3,
    timeMin: 10,
    description: 'y\' = −½y + 2 avec y(0) = 10 : la solution 6e^(−x/2) + 4 converge vers 4.',
    xpReward: 100,
  },
  {
    id: 'equadiff-14',
    number: 14,
    tier: 3,
    title: 'Croissance de population',
    notion: 'Modélisation',
    difficulty: 3,
    timeMin: 10,
    description: 'P\' = 0,02P avec P(0) = 1000 : P(t) = 1000e^(0,02t), P(50) ≈ 2718.',
    xpReward: 100,
  },
  {
    id: 'equadiff-15',
    number: 15,
    tier: 3,
    title: 'Charge d\'un condensateur',
    notion: 'Modélisation',
    difficulty: 3,
    timeMin: 12,
    description: 'u\' = −2u + 10 avec u(0) = 0 : u(t) = 5(1−e^(−2t)) tend vers 5.',
    xpReward: 100,
  },
  // ── TIER 4 — Sujets type bac ◆ ───────────────────────────────────────────
  {
    id: 'equadiff-16',
    number: 16,
    tier: 4,
    title: 'Bac — Étude complète',
    notion: 'Équation y\' = ay + b',
    difficulty: 4,
    timeMin: 18,
    description: '(E) : y\' = −2y + 8 : solutions générales, équilibre, Cauchy, variations et limite.',
    xpReward: 150,
  },
  {
    id: 'equadiff-17',
    number: 17,
    tier: 4,
    title: 'Bac — La tasse de thé',
    notion: 'Modélisation',
    difficulty: 4,
    timeMin: 20,
    description: 'T\' = −0,04(T−22), T(0) = 85 : mise en forme, résolution, T(30) ≈ 41,0°, limite 22°.',
    xpReward: 150,
  },
  {
    id: 'equadiff-18',
    number: 18,
    tier: 4,
    title: 'Bac — Fonction auxiliaire',
    notion: 'Changement de fonction',
    difficulty: 4,
    timeMin: 20,
    description: 'Poser g = f − 3 pour ramener y\' = 2y − 6 à y\' = 2y, puis vérifier en direct.',
    xpReward: 150,
  },
];

// ─── Module : Fonctions sinus & cosinus ────────────────────────────────────
const TRIGO_LEVELS: ModuleLevel[] = [
  // ── TIER 0 — QCM ─────────────────────────────────────────────────────────
  {
    id: 'trigo-qcm',
    number: 0,
    tier: 0,
    title: 'QCM Flash',
    notion: 'Tout le cours',
    difficulty: 0,
    timeMin: 12,
    description: '10 questions pour vérifier que le cours est en place avant de passer aux exercices.',
    xpReward: 30,
  },
  // ── TIER 1 — Automatismes ★ ───────────────────────────────────────────────
  {
    id: 'trigo-1',
    number: 1,
    tier: 1,
    title: 'Valeurs remarquables',
    notion: 'Cercle trigonométrique',
    difficulty: 1,
    timeMin: 8,
    description: 'cos(2π/3), sin(5π/6), cos(−π/4), sin(3π/4) avec les angles associés.',
    xpReward: 40,
  },
  {
    id: 'trigo-2',
    number: 2,
    tier: 1,
    title: 'Dérivées de base',
    notion: 'Dérivation',
    difficulty: 1,
    timeMin: 7,
    description: 'Dériver sin(3x), cos(2x) et sin x + cos x avec les formules composées.',
    xpReward: 40,
  },
  {
    id: 'trigo-3',
    number: 3,
    tier: 1,
    title: 'Limite sin(2x)/x',
    notion: 'Limites',
    difficulty: 1,
    timeMin: 6,
    description: 'Faire apparaître sin(2x)/2x pour utiliser la limite de référence : résultat 2.',
    xpReward: 40,
  },
  {
    id: 'trigo-4',
    number: 4,
    tier: 1,
    title: 'Équation cos x = √2/2',
    notion: 'Équations',
    difficulty: 1,
    timeMin: 7,
    description: 'Reconnaître cos(π/4) et appliquer la formule de référence sur [0;2π[.',
    xpReward: 40,
  },
  // ── TIER 2 — Méthodes ★★ ─────────────────────────────────────────────────
  {
    id: 'trigo-5',
    number: 5,
    tier: 2,
    title: 'Simplification d\'expressions',
    notion: 'Angles associés',
    difficulty: 2,
    timeMin: 8,
    description: 'Réduire cos(−x) + sin(π/2−x) et sin(π−x) − sin(−x) avec les angles associés.',
    xpReward: 70,
  },
  {
    id: 'trigo-6',
    number: 6,
    tier: 2,
    title: 'Démonstration cos(π/2 + x)',
    notion: 'Angles associés',
    difficulty: 2,
    timeMin: 8,
    description: 'Prouver que cos(π/2+x) = −sin x par rotation d\'un quart de tour sur le cercle.',
    xpReward: 70,
  },
  {
    id: 'trigo-7',
    number: 7,
    tier: 2,
    title: 'Dérivée de x sin x',
    notion: 'Dérivation',
    difficulty: 2,
    timeMin: 7,
    description: 'Règle du produit : (x sin x)\' = sin x + x cos x.',
    xpReward: 70,
  },
  {
    id: 'trigo-8',
    number: 8,
    tier: 2,
    title: 'Dérivée de cos(x²)',
    notion: 'Dérivation',
    difficulty: 2,
    timeMin: 7,
    description: 'Composée avec u = x² : résultat −2x sin(x²).',
    xpReward: 70,
  },
  {
    id: 'trigo-9',
    number: 9,
    tier: 2,
    title: 'Dérivée de sin²x',
    notion: 'Dérivation',
    difficulty: 2,
    timeMin: 8,
    description: 'Dériver (sin x)² et reconnaître la duplication : 2 sin x cos x = sin(2x).',
    xpReward: 70,
  },
  {
    id: 'trigo-10',
    number: 10,
    tier: 2,
    title: 'Limite sin(5x)/3x',
    notion: 'Limites',
    difficulty: 2,
    timeMin: 7,
    description: 'Factoriser 5/3 devant sin(5x)/5x : limite 5/3.',
    xpReward: 70,
  },
  {
    id: 'trigo-11',
    number: 11,
    tier: 2,
    title: 'Limite sin x/2x',
    notion: 'Limites',
    difficulty: 2,
    timeMin: 6,
    description: 'Extraire le facteur ½ devant la limite de référence : résultat ½.',
    xpReward: 70,
  },
  {
    id: 'trigo-12',
    number: 12,
    tier: 2,
    title: 'Équation sin x = 1/2',
    notion: 'Équations',
    difficulty: 2,
    timeMin: 8,
    description: 'Reconnaître sin(π/6) : solutions π/6 et 5π/6 sur [0;2π[.',
    xpReward: 70,
  },
  {
    id: 'trigo-13',
    number: 13,
    tier: 2,
    title: 'Équation cos x = −1/2',
    notion: 'Équations',
    difficulty: 2,
    timeMin: 8,
    description: 'Écrire −1/2 = cos(2π/3) : solutions 2π/3 et 4π/3 sur [0;2π[.',
    xpReward: 70,
  },
  {
    id: 'trigo-14',
    number: 14,
    tier: 2,
    title: 'Variations de cos x',
    notion: 'Étude de fonctions',
    difficulty: 2,
    timeMin: 9,
    description: 'f\' = −sin x sur [0;2π] : décroît puis croît, max 1 en 0 et 2π, min −1 en π.',
    xpReward: 70,
  },
  // ── TIER 3 — Approfondissement ★★★ ───────────────────────────────────────
  {
    id: 'trigo-15',
    number: 15,
    tier: 3,
    title: 'Équation 2 sin x − 1 = 0',
    notion: 'Équations',
    difficulty: 3,
    timeMin: 9,
    description: 'Isoler le sinus avant de résoudre : sin x = ½ donne π/6 et 5π/6.',
    xpReward: 100,
  },
  {
    id: 'trigo-16',
    number: 16,
    tier: 3,
    title: 'Étude de sin(2x)',
    notion: 'Étude de fonctions',
    difficulty: 3,
    timeMin: 12,
    description: 'f\' = 2cos(2x) sur [0;π] : sinusoïde comprimée, max 1 en π/4, min −1 en 3π/4.',
    xpReward: 100,
  },
  {
    id: 'trigo-17',
    number: 17,
    tier: 3,
    title: 'Monotonie de x + sin x',
    notion: 'Étude de fonctions',
    difficulty: 3,
    timeMin: 10,
    description: 'f\' = 1 + cos x ≥ 0 : croissante sur ℝ malgré les oscillations du sinus.',
    xpReward: 100,
  },
  // ── TIER 4 — Sujets type bac ◆ ───────────────────────────────────────────
  {
    id: 'trigo-18',
    number: 18,
    tier: 4,
    title: 'Bac — Étude de sin x + cos x',
    notion: 'Étude complète',
    difficulty: 4,
    timeMin: 20,
    description: 'f\' = cos x − sin x, tan x = 1, variations complètes, max √2 en π/4, min −√2 en 5π/4.',
    xpReward: 150,
  },
  {
    id: 'trigo-19',
    number: 19,
    tier: 4,
    title: 'Bac — Équation du 2ᵈ degré',
    notion: 'Changement de variable',
    difficulty: 4,
    timeMin: 18,
    description: 'Poser X = cos x dans 2cos²x − cos x − 1 = 0 : solutions 0, 2π/3, 4π/3.',
    xpReward: 150,
  },
  {
    id: 'trigo-20',
    number: 20,
    tier: 4,
    title: 'Bac — Inégalité sin x ≤ x',
    notion: 'Étude + inégalité',
    difficulty: 4,
    timeMin: 18,
    description: 'Étudier f(x) = x − sin x : f\' = 1 − cos x ≥ 0, f(0) = 0, d\'où sin x ≤ x sur [0;2π].',
    xpReward: 150,
  },
];

// ─── Module : Combinatoire & dénombrement ──────────────────────────────────
const COMBINATOIRE_LEVELS: ModuleLevel[] = [
  // ── TIER 0 — QCM ─────────────────────────────────────────────────────────
  {
    id: 'combinatoire-qcm',
    number: 0,
    tier: 0,
    title: 'QCM Flash',
    notion: 'Tout le cours',
    difficulty: 0,
    timeMin: 12,
    description: '10 questions pour vérifier que le cours est en place avant de passer aux exercices.',
    xpReward: 30,
  },
  // ── TIER 1 — Automatismes ★ ───────────────────────────────────────────────
  {
    id: 'combinatoire-1',
    number: 1,
    tier: 1,
    title: 'Codes & plaques',
    notion: 'k-uplets',
    difficulty: 1,
    timeMin: 7,
    description: 'Compter les codes à 4 chiffres (10⁴) et les plaques 2 lettres + 3 chiffres (26²×10³).',
    xpReward: 40,
  },
  {
    id: 'combinatoire-2',
    number: 2,
    tier: 1,
    title: 'Le menu du restaurant',
    notion: 'Principe multiplicatif',
    difficulty: 1,
    timeMin: 5,
    description: '4 entrées × 5 plats × 3 desserts = 60 repas par le principe multiplicatif.',
    xpReward: 40,
  },
  {
    id: 'combinatoire-3',
    number: 3,
    tier: 1,
    title: 'Calculs d\'arrangements',
    notion: 'Arrangements',
    difficulty: 1,
    timeMin: 6,
    description: 'Calculer A(7,3) = 7×6×5 et A(10,2) = 10×9.',
    xpReward: 40,
  },
  {
    id: 'combinatoire-4',
    number: 4,
    tier: 1,
    title: 'Rangements & anagrammes',
    notion: 'Permutations',
    difficulty: 1,
    timeMin: 6,
    description: 'Ranger 6 livres (6!) et compter les anagrammes de LIVRE (5!).',
    xpReward: 40,
  },
  {
    id: 'combinatoire-5',
    number: 5,
    tier: 1,
    title: 'Calculs de combinaisons',
    notion: 'Combinaisons',
    difficulty: 1,
    timeMin: 6,
    description: 'Calculer C(8,3) = 56 et C(10,2) = 45 avec la formule du coefficient binomial.',
    xpReward: 40,
  },
  {
    id: 'combinatoire-6',
    number: 6,
    tier: 1,
    title: 'Symétrie du binomial',
    notion: 'Propriétés',
    difficulty: 1,
    timeMin: 6,
    description: 'Constater C(7,2) = C(7,5) = 21 : la propriété de symétrie C(n,k) = C(n,n−k).',
    xpReward: 40,
  },
  // ── TIER 2 — Méthodes ★★ ─────────────────────────────────────────────────
  {
    id: 'combinatoire-7',
    number: 7,
    tier: 2,
    title: 'Tirages avec remise',
    notion: 'k-uplets',
    difficulty: 2,
    timeMin: 7,
    description: 'Dé lancé 3 fois (6³ = 216) et 2 tirages avec remise parmi 5 (5² = 25).',
    xpReward: 70,
  },
  {
    id: 'combinatoire-8',
    number: 8,
    tier: 2,
    title: 'Le podium',
    notion: 'Arrangements',
    difficulty: 2,
    timeMin: 7,
    description: 'Podium de 12 coureurs : ordre important sans répétition, A(12,3) = 1320.',
    xpReward: 70,
  },
  {
    id: 'combinatoire-9',
    number: 9,
    tier: 2,
    title: 'Mots de lettres distinctes',
    notion: 'Arrangements',
    difficulty: 2,
    timeMin: 7,
    description: 'Mots de 4 lettres distinctes sur 26 : A(26,4) = 358 800.',
    xpReward: 70,
  },
  {
    id: 'combinatoire-10',
    number: 10,
    tier: 2,
    title: 'Mains de cartes',
    notion: 'Combinaisons',
    difficulty: 2,
    timeMin: 7,
    description: 'Mains de 5 cartes parmi 32 : tirage simultané, C(32,5) = 201 376.',
    xpReward: 70,
  },
  {
    id: 'combinatoire-11',
    number: 11,
    tier: 2,
    title: 'Le comité',
    notion: 'Combinaisons',
    difficulty: 2,
    timeMin: 7,
    description: 'Comités de 4 élèves parmi 20 sans rôle : C(20,4) = 4845.',
    xpReward: 70,
  },
  {
    id: 'combinatoire-12',
    number: 12,
    tier: 2,
    title: 'Règle de Pascal',
    notion: 'Triangle de Pascal',
    difficulty: 2,
    timeMin: 7,
    description: 'Vérifier C(6,3) = C(5,2) + C(5,3) = 20 par le calcul.',
    xpReward: 70,
  },
  {
    id: 'combinatoire-13',
    number: 13,
    tier: 2,
    title: 'Développer (x+2)³',
    notion: 'Binôme de Newton',
    difficulty: 2,
    timeMin: 9,
    description: 'Appliquer la formule du binôme : x³ + 6x² + 12x + 8.',
    xpReward: 70,
  },
  {
    id: 'combinatoire-14',
    number: 14,
    tier: 2,
    title: 'Les trois modèles de tirage',
    notion: 'Choisir le modèle',
    difficulty: 2,
    timeMin: 10,
    description: 'Une urne, 3 boules tirées : simultané (120), sans remise (720), avec remise (1000).',
    xpReward: 70,
  },
  // ── TIER 3 — Approfondissement ★★★ ───────────────────────────────────────
  {
    id: 'combinatoire-15',
    number: 15,
    tier: 3,
    title: 'Comité mixte',
    notion: 'Combinaisons + multiplicatif',
    difficulty: 3,
    timeMin: 9,
    description: '2 femmes parmi 6 ET 2 hommes parmi 5 : C(6,2)×C(5,2) = 150.',
    xpReward: 100,
  },
  {
    id: 'combinatoire-16',
    number: 16,
    tier: 3,
    title: 'Coefficient de x²',
    notion: 'Binôme de Newton',
    difficulty: 3,
    timeMin: 10,
    description: 'Isoler le terme k = 2 dans (2x+1)⁵ : coefficient C(5,2)×2² = 40.',
    xpReward: 100,
  },
  {
    id: 'combinatoire-17',
    number: 17,
    tier: 3,
    title: 'Les mots de CLAVIER',
    notion: 'Arrangements',
    difficulty: 3,
    timeMin: 9,
    description: 'Mots de 5 lettres distinctes parmi les 7 de CLAVIER : A(7,5) = 2520.',
    xpReward: 100,
  },
  {
    id: 'combinatoire-18',
    number: 18,
    tier: 3,
    title: 'Au moins une femme',
    notion: 'Complémentaire',
    difficulty: 3,
    timeMin: 10,
    description: 'Compter par le complémentaire : 84 jurys au total, 10 sans femme, donc 74.',
    xpReward: 100,
  },
  // ── TIER 4 — Sujets type bac ◆ ───────────────────────────────────────────
  {
    id: 'combinatoire-19',
    number: 19,
    tier: 4,
    title: 'Bac — Bureau mixte',
    notion: 'Combinaisons',
    difficulty: 4,
    timeMin: 18,
    description: '8 femmes, 6 hommes, bureau de 4 : total 1001, exactement 2F/2H = 420, au moins 3F = 406.',
    xpReward: 150,
  },
  {
    id: 'combinatoire-20',
    number: 20,
    tier: 4,
    title: 'Bac — Urne bicolore',
    notion: 'Dénombrement + probas',
    difficulty: 4,
    timeMin: 20,
    description: '5 rouges, 3 vertes, tirage de 3 : dénombrements puis P(2 rouges) = 15/28.',
    xpReward: 150,
  },
  {
    id: 'combinatoire-21',
    number: 21,
    tier: 4,
    title: 'Bac — Binôme & sommes',
    notion: 'Binôme de Newton',
    difficulty: 4,
    timeMin: 18,
    description: 'Développer (1+x)⁴ puis évaluer en x = ±1 : Σ C(4,k) = 16 et somme alternée = 0.',
    xpReward: 150,
  },
];

export const MATHS_MODULES: PhysicsModule[] = [
  {
    id: 'math-suites',
    subject: 'Maths',
    level: 'Terminale',
    title: 'Suites & Récurrence',
    subtitle: 'Récurrence · Limites · Suites récurrentes',
    accentHsl: '270 65% 62%',
    pdfCours:     null,
    pdfFiche:     null,
    pdfExercices: null,
    levels: SUITES_LEVELS,
  },
  {
    id: 'maths-fonctions',
    subject: 'Maths',
    level: 'Terminale',
    title: 'Les fonctions',
    subtitle: 'Limites · Dérivation · Convexité · TVI',
    accentHsl: '270 65% 62%',
    pdfCours:     null,
    pdfFiche:     null,
    pdfExercices: null,
    levels: FONCTIONS_LEVELS,
  },
  {
    id: 'maths-logarithme',
    subject: 'Maths',
    level: 'Terminale',
    title: 'Le logarithme népérien',
    subtitle: 'Définition · Propriétés · Dérivation · Équations',
    accentHsl: '270 65% 62%',
    pdfCours:     null,
    pdfFiche:     null,
    pdfExercices: null,
    levels: LOGARITHME_LEVELS,
  },
  {
    id: 'maths-probabilites',
    subject: 'Maths',
    level: 'Terminale',
    title: 'Probabilités & loi binomiale',
    subtitle: 'Conditionnelles · Indépendance · Binomiale · Grands nombres',
    accentHsl: '270 65% 62%',
    pdfCours:     null,
    pdfFiche:     null,
    pdfExercices: null,
    levels: PROBABILITES_LEVELS,
  },
  {
    id: 'maths-geometrie',
    subject: 'Maths',
    level: 'Terminale',
    title: 'Géométrie dans l\'espace',
    subtitle: 'Vecteurs · Droites · Plans · Produit scalaire · Distances',
    accentHsl: '270 65% 62%',
    pdfCours:     null,
    pdfFiche:     null,
    pdfExercices: null,
    levels: GEOMETRIE_LEVELS,
  },
  {
    id: 'maths-primitives',
    subject: 'Maths',
    level: 'Terminale',
    title: 'Primitives & intégrales',
    subtitle: 'Primitives · Intégrale & aire · Valeur moyenne · IPP',
    accentHsl: '270 65% 62%',
    pdfCours:     null,
    pdfFiche:     null,
    pdfExercices: null,
    levels: PRIMITIVES_LEVELS,
  },
  {
    id: 'maths-exponentielle',
    subject: 'Maths',
    level: 'Terminale',
    title: 'Fonction exponentielle',
    subtitle: 'Définition · Algèbre · Dérivées · Croissances comparées',
    accentHsl: '270 65% 62%',
    pdfCours:     null,
    pdfFiche:     null,
    pdfExercices: null,
    levels: EXPONENTIELLE_LEVELS,
  },
  {
    id: 'maths-equadiff',
    subject: 'Maths',
    level: 'Terminale',
    title: 'Équations différentielles',
    subtitle: 'y\' = ay · y\' = ay + b · Cauchy · Modélisation',
    accentHsl: '270 65% 62%',
    pdfCours:     null,
    pdfFiche:     null,
    pdfExercices: null,
    levels: EQUADIFF_LEVELS,
  },
  {
    id: 'maths-trigo',
    subject: 'Maths',
    level: 'Terminale',
    title: 'Fonctions sinus & cosinus',
    subtitle: 'Cercle trigo · Dérivées · Limites · Équations',
    accentHsl: '270 65% 62%',
    pdfCours:     null,
    pdfFiche:     null,
    pdfExercices: null,
    levels: TRIGO_LEVELS,
  },
  {
    id: 'maths-combinatoire',
    subject: 'Maths',
    level: 'Terminale',
    title: 'Combinatoire & dénombrement',
    subtitle: 'k-uplets · Arrangements · Combinaisons · Binôme',
    accentHsl: '270 65% 62%',
    pdfCours:     null,
    pdfFiche:     null,
    pdfExercices: null,
    levels: COMBINATOIRE_LEVELS,
  },
];

export const ALL_MODULES = [...PHYSICS_MODULES, ...MATHS_MODULES];

export const TIER_META = [
  { tier: 0 as const, label: 'VÉRIF COURS',       sub: 'QCM Flash',              hsl: '205 85% 60%' },
  { tier: 1 as const, label: 'AUTOMATISMES ★',    sub: 'Une notion = un exercice', hsl: '142 65% 48%' },
  { tier: 2 as const, label: 'MÉTHODES ★★',       sub: 'Les méthodes types',       hsl: '43 90% 52%'  },
  { tier: 3 as const, label: 'TYPE BAC ★★★',      sub: 'Les problèmes complets',   hsl: '270 60% 62%' },
  { tier: 4 as const, label: 'DÉFIS ◆',           sub: 'Pour aller plus loin',     hsl: '0 70% 60%'   },
];

export const DIFF_LABEL = ['QCM', '★', '★★', '★★★', '◆'];
