import type { Accessory } from './types';

// ─────────────────────────────────────────────────────────────
// Full accessory catalog — 25 items across 5 slots
// ─────────────────────────────────────────────────────────────

export const ACCESSORIES: Accessory[] = [

  // ── HATS ──────────────────────────────────────────────────
  {
    id: 'hat_beanie',
    slot: 'hat',
    label: 'Bonnet étudiant',
    emoji: '🪖',
    description: 'Le classique bonnet de révision.',
    condition: { type: 'free', label: 'Disponible dès le début' },
    rarity: 'common',
    riveInput: 'hat',
    riveValue: 1,
  },
  {
    id: 'hat_graduation',
    slot: 'hat',
    label: 'Toque de diplômé',
    emoji: '🎓',
    description: 'La toque des grands jours. Tu la mérites.',
    condition: { type: 'level', value: 5, label: 'Niveau 5' },
    rarity: 'rare',
    riveInput: 'hat',
    riveValue: 2,
  },
  {
    id: 'hat_beret',
    slot: 'hat',
    label: 'Béret intellectuel',
    emoji: '🪅',
    description: 'L\'indispensable du penseur parisien.',
    condition: { type: 'streak', value: 7, label: 'Streak 7 jours' },
    rarity: 'rare',
    riveInput: 'hat',
    riveValue: 3,
  },
  {
    id: 'hat_wizard',
    slot: 'hat',
    label: 'Chapeau de sorcier',
    emoji: '🧙',
    description: 'La maîtrise du deepwork t\'a accordé des pouvoirs.',
    condition: { type: 'deepwork_sessions', value: 50, label: '50 sessions deepwork' },
    rarity: 'epic',
    riveInput: 'hat',
    riveValue: 4,
  },
  {
    id: 'hat_crown',
    slot: 'hat',
    label: 'Couronne d\'or',
    emoji: '👑',
    description: 'Réservée aux légendes du tableau de bord.',
    condition: { type: 'level', value: 50, label: 'Niveau 50' },
    rarity: 'legendary',
    riveInput: 'hat',
    riveValue: 5,
  },

  // ── GLASSES ───────────────────────────────────────────────
  {
    id: 'glasses_round',
    slot: 'glasses',
    label: 'Lunettes rondes',
    emoji: '👓',
    description: 'Le style bibliothèque intemporel.',
    condition: { type: 'free', label: 'Disponible dès le début' },
    rarity: 'common',
    riveInput: 'glasses',
    riveValue: 1,
  },
  {
    id: 'glasses_smart',
    slot: 'glasses',
    label: 'Lunettes d\'intello',
    emoji: '🥸',
    description: 'Plus tu travailles, plus tu les portes bien.',
    condition: { type: 'level', value: 10, label: 'Niveau 10' },
    rarity: 'rare',
    riveInput: 'glasses',
    riveValue: 2,
  },
  {
    id: 'glasses_gaming',
    slot: 'glasses',
    label: 'Visière gaming',
    emoji: '🕶️',
    description: 'Pour ceux qui voient le travail comme un jeu.',
    condition: { type: 'deepwork_sessions', value: 10, label: '10 sessions deepwork' },
    rarity: 'rare',
    riveInput: 'glasses',
    riveValue: 3,
  },
  {
    id: 'glasses_monocle',
    slot: 'glasses',
    label: 'Monocle élégant',
    emoji: '🧐',
    description: 'Porté par ceux qui ne font jamais rien à moitié.',
    condition: { type: 'xp', value: 5000, label: '5 000 XP' },
    rarity: 'epic',
    riveInput: 'glasses',
    riveValue: 4,
  },

  // ── OUTFITS ───────────────────────────────────────────────
  {
    id: 'outfit_hoodie',
    slot: 'outfit',
    label: 'Hoodie étudiant',
    emoji: '👕',
    description: 'Confort total pour les longues sessions.',
    condition: { type: 'free', label: 'Disponible dès le début' },
    rarity: 'common',
    riveInput: 'outfit',
    riveValue: 1,
  },
  {
    id: 'outfit_uniform',
    slot: 'outfit',
    label: 'Uniforme élite',
    emoji: '🎽',
    description: 'Rigueur et discipline. Chaque jour.',
    condition: { type: 'streak', value: 30, label: 'Streak 30 jours' },
    rarity: 'rare',
    riveInput: 'outfit',
    riveValue: 2,
  },
  {
    id: 'outfit_suit',
    slot: 'outfit',
    label: 'Costume classe',
    emoji: '🤵',
    description: 'Pour les grandes occasions et les grandes ambitions.',
    condition: { type: 'xp', value: 10000, label: '10 000 XP' },
    rarity: 'epic',
    riveInput: 'outfit',
    riveValue: 3,
  },
  {
    id: 'outfit_toga',
    slot: 'outfit',
    label: 'Toge dorée',
    emoji: '👘',
    description: 'La tenue des diplômés des grandes écoles.',
    condition: { type: 'level', value: 25, label: 'Niveau 25' },
    rarity: 'epic',
    riveInput: 'outfit',
    riveValue: 4,
  },
  {
    id: 'outfit_armor',
    slot: 'outfit',
    label: 'Armure du guerrier',
    emoji: '⚔️',
    description: 'Pour ceux qui ont bravé 100 sessions de deepwork.',
    condition: { type: 'deepwork_sessions', value: 100, label: '100 sessions deepwork' },
    rarity: 'legendary',
    riveInput: 'outfit',
    riveValue: 5,
  },

  // ── BACKGROUNDS ───────────────────────────────────────────
  {
    id: 'bg_classroom',
    slot: 'background',
    label: 'Salle de cours',
    emoji: '🏫',
    description: 'Le cadre familier du quotidien étudiant.',
    condition: { type: 'free', label: 'Disponible dès le début' },
    rarity: 'common',
    riveInput: 'background',
    riveValue: 1,
  },
  {
    id: 'bg_library',
    slot: 'background',
    label: 'Bibliothèque royale',
    emoji: '📚',
    description: 'Des milliers de livres pour t\'inspirer.',
    condition: { type: 'level', value: 10, label: 'Niveau 10' },
    rarity: 'rare',
    riveInput: 'background',
    riveValue: 2,
  },
  {
    id: 'bg_dungeon',
    slot: 'background',
    label: 'Donjon mystique',
    emoji: '🏰',
    description: 'Un cadre obscur pour des sessions profondes.',
    condition: { type: 'deepwork_sessions', value: 50, label: '50 sessions deepwork' },
    rarity: 'epic',
    riveInput: 'background',
    riveValue: 3,
  },
  {
    id: 'bg_sorbonne',
    slot: 'background',
    label: 'Sorbonne dorée',
    emoji: '🎭',
    description: 'La cour de la Sorbonne au coucher du soleil.',
    condition: { type: 'level', value: 25, label: 'Niveau 25' },
    rarity: 'epic',
    riveInput: 'background',
    riveValue: 4,
  },
  {
    id: 'bg_paris',
    slot: 'background',
    label: 'Paris la nuit',
    emoji: '🗼',
    description: 'La Tour Eiffel illuminée pour les grands esprits.',
    condition: { type: 'xp', value: 15000, label: '15 000 XP' },
    rarity: 'legendary',
    riveInput: 'background',
    riveValue: 5,
  },
  {
    id: 'bg_space',
    slot: 'background',
    label: 'Espace infini',
    emoji: '🌌',
    description: 'Pour ceux dont les ambitions n\'ont pas de limites.',
    condition: { type: 'level', value: 50, label: 'Niveau 50' },
    rarity: 'legendary',
    riveInput: 'background',
    riveValue: 6,
  },

  // ── BADGES ────────────────────────────────────────────────
  {
    id: 'badge_scholar',
    slot: 'badge',
    label: 'Érudit',
    emoji: '📖',
    description: 'La connaissance avant tout.',
    condition: { type: 'free', label: 'Disponible dès le début' },
    rarity: 'common',
    riveInput: 'badge',
    riveValue: 1,
  },
  {
    id: 'badge_flame',
    slot: 'badge',
    label: 'Flamme éternelle',
    emoji: '🔥',
    description: 'Pour ceux qui ne s\'arrêtent jamais.',
    condition: { type: 'streak', value: 7, label: 'Streak 7 jours' },
    rarity: 'rare',
    riveInput: 'badge',
    riveValue: 2,
  },
  {
    id: 'badge_brain',
    slot: 'badge',
    label: 'Cerveau d\'or',
    emoji: '🧠',
    description: 'La maîtrise intellectuelle totale.',
    condition: { type: 'xp', value: 10000, label: '10 000 XP' },
    rarity: 'epic',
    riveInput: 'badge',
    riveValue: 3,
  },
  {
    id: 'badge_champion',
    slot: 'badge',
    label: 'Champion',
    emoji: '🏆',
    description: 'Cent jours de discipline. Indestructible.',
    condition: { type: 'streak', value: 100, label: 'Streak 100 jours' },
    rarity: 'legendary',
    riveInput: 'badge',
    riveValue: 4,
  },
  {
    id: 'badge_elite',
    slot: 'badge',
    label: 'Élite',
    emoji: '⚡',
    description: 'Le sommet de l\'ascension.',
    condition: { type: 'level', value: 50, label: 'Niveau 50' },
    rarity: 'legendary',
    riveInput: 'badge',
    riveValue: 5,
  },
];

/** Lookup a single accessory by id */
export function getAccessory(id: string): Accessory | undefined {
  return ACCESSORIES.find(a => a.id === id);
}

/** Get all accessories for a given slot */
export function getAccessoriesBySlot(slot: Accessory['slot']): Accessory[] {
  return ACCESSORIES.filter(a => a.slot === slot);
}
